### ISSUE TITLE
Cache the navigation menu

### ISSUE THREAD

**Issue by samilliken** [samilliken/openDCIM#1002]
On installations with a very large number of datacenters/zones/containers/rows, there is a significant amount of processing time spent building the navigation menu.    Rather than taking that hit on every page load, build it only when something changes and pull the cached version from the db on page loads.

**Comment by samilliken** [comment]
To do:

This will need to be turned into a config option because if you cache the menu, it can't be tailored based on each user's rights.    Whether they can actually see inside of a cabinet is still controlled by the security plan, but everybody will be able to see the tree if it's turned on.

**Comment by samilliken** [comment]
Can you test this on a copy of your db?

Scott

**Comment by ikcilabd** [comment]
I will try.  Still on 4.3 but will look at getting a sandbox up in 4.5 schema if that's necessary to test.

**Comment by ikcilabd** [comment]
Ok, got the sandbox up, getting a partial nav tree.  Looks like the NavMenu value is hitting the MySQL DB byte limit (65535 bytes)

**Comment by ikcilabd** [comment]
Looks like I'd need a type that can handle upwards of 400kB so changed the Value type to mediumtext (max of like 16MB) and moved a cabinet from/to a row to initiate a new build of the tree.  Performance is great, total time in a refresh to Home is 75ms compared to 1895ms...good stuff Sam

**Comment by samilliken** [comment]
Now that sounds very good.    At least we know we're going down a valid path for optimization.
