### ISSUE TITLE
Unable to bind to LDAP (AD)

### ISSUE THREAD

**Issue by mfleurisson** [samilliken/openDCIM#1005]
[Thu Jan 25 11:21:23.420386 2018] [:error] [pid 1516] [client 10.252.222.72:50345] PHP Warning:  ldap_bind(): Unable to bind to server: Can't contact LDAP server in /opt/openDCIM/opendcim/ldap_bootstrap.php on line 20, referer: https://xxxxxx.xxxx.lan/ldap_bootstrap.php
[Thu Jan 25 11:21:23.420526 2018] [:error] [pid 1516] [client 10.252.222.72:50345] PHP Notice:  Undefined variable: config in /opt/openDCIM/opendcim/header.inc.php on line 4, referer: https://xxxxxx.xxxx.lan/ldap_bootstrap.php
[Thu Jan 25 11:21:23.420552 2018] [:error] [pid 1516] [client 10.252.222.72:50345] PHP Notice:  Trying to get property of non-object in /opt/openDCIM/opendcim/header.inc.php on line 4, referer: https://xxxxxx.xxxx.lan/ldap_bootstrap.php
[Thu Jan 25 11:21:23.420560 2018] [:error] [pid 1516] [client 10.252.222.72:50345] PHP Notice:  Undefined variable: person in /opt/openDCIM/opendcim/header.inc.php on line 10, referer: https://xxxxxx.xxxx.lan/ldap_bootstrap.php
[Thu Jan 25 11:21:23.420563 2018] [:error] [pid 1516] [client 10.252.222.72:50345] PHP Notice:  Trying to get property of non-object in /opt/openDCIM/opendcim/header.inc.php on line 10, referer: https://xxxxxx.xxxx.lan/ldap_bootstrap.php

**Comment by samilliken** [comment]
Send your inquiry to the mailing list, not Github.    This isn't a bug, it's a local configuration issue.
