### ISSUE TITLE
Layout bug

### ISSUE THREAD

**Issue by wilpig** [samilliken/openDCIM#1006]
http://dev.opendcim.org/cabrow.php
<img width="630" alt="screenshot 2018-01-26 22 45 05" src="https://user-images.githubusercontent.com/1653882/35468756-9c291440-02ea-11e8-894e-074e1f655044.png">

Looks like at some point we added the drop down plugin to this and didn't adjust styles.

**Comment by wilpig** [comment]
I didnt add the dropdown plugin there. :P

**Comment by wilpig** [comment]
#969 <-- culprit

**Comment by samilliken** [comment]
Guilty.   Now fix it, because you know how bad I am with CSS layout.
