### ISSUE TITLE
Display problem - Mozila Firefox

### ISSUE THREAD

**Issue by ivoIT1** [samilliken/openDCIM#1008]
Did someone has asme experience like me ?
There is problem with displaying port list of device on port position 22
![obrazek](https://user-images.githubusercontent.com/35807719/35528906-9c9994f8-052f-11e8-94c1-5b46d4a637db.png)
First I thought is problem of my DB, then I have found the same happen on the Demo on internet
IE works fine
Chome is OK too

**Comment by wilpig** [comment]
This is not enough information to follow to view as a bug report.  If this is a question then take it to the mailing list.  If it is a bug report then at the very least it needs to include what version, and the steps required to recreate this problem.

**Comment by samilliken** [comment]
If this shows on the openDCIM demo site (version 4.5), then what's the device you're looking at?

Scott

**Comment by wilpig** [comment]
Based on the actions log I can see that this device was created about the time of this report.  http://opendcim.org/demo/devices.php?DeviceID=22  but port 22 looks fine to me.

<img width="580" alt="screenshot 2018-01-29 13 54 23" src="https://user-images.githubusercontent.com/1653882/35531211-f0a6a4b6-04fb-11e8-93b0-49dc6ff26b06.png">

**Comment by samilliken** [comment]
Yep, I just checked that device in both Chrome and Firefox.   I'm not seeing any display issues.

**Comment by wilpig** [comment]
Problem unable to be recreated.
