### ISSUE TITLE
Notes field in devices.php won't properly resize

### ISSUE THREAD

**Issue by baltimoresports** [samilliken/openDCIM#1009]
If the notes in a device are larger then the text box, them it bleeds out. 

![textbox issue](https://user-images.githubusercontent.com/1420685/35653329-b75c1e78-06b5-11e8-902b-549847de4164.PNG)

**Comment by wilpig** [comment]
Please try that on dev.opendcim.org I've changed out the notes plugin for the next release

**Comment by baltimoresports** [comment]
Works great on Dev! Any way I can implement that feature now?

**Comment by wilpig** [comment]
Not easily.  I correct that in this issue.  https://github.com/samilliken/openDCIM/issues/997  I'll be closing this now.
