### ISSUE TITLE
vmnamecheck.php doesn't run without an updated swiftmailer path

### ISSUE THREAD

**Issue by codhopper** [samilliken/openDCIM#1010]
vmnamecheck.php stopped deleting/updating VMs a while ago. I've done a quick bit of investigation and it looks like the path hasn't been updated. 

It is working well once updated to the full path. I take it the libraries moved sometime a while ago and no-one has used this script since. 
```
require_once('vendor/swiftmailer/swiftmailer/lib/swift_required.php');
```

The error looks a little like this: 
```
[<user>@<server> opendcim]#  /usr/bin/php /var/www/opendcim/vmnamecheck.php
PHP Warning:  require_once(swiftmailer/swift_required.php): failed to open stream: No such file or directory in /var/www/opendcim/vmnamecheck.php on line 4
PHP Fatal error:  require_once(): Failed opening required 'swiftmailer/swift_required.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/opendcim/vmnamecheck.php on line 4
```

**Comment by codhopper** [comment]
Related to issue #887. After reading that it would be better to completely remove the line. 

I tried commenting out the line and it worked equally as well.

**Comment by samilliken** [comment]
These should be updated to use the autoloader for continued future compatibility.
