### ISSUE TITLE
Feature Request: Show disposal "rooms".

### ISSUE THREAD

**Issue by sv3nster** [samilliken/openDCIM#1015]
First off, thanks for this great project!

I would like to request the ability to view previously disposed assets, similar to browsing the "storage room", but maybe also ordered by date. Sometimes we get requests like: "how many IBM servers were returned to lessors last year?". It would be helpful to be able to view these as a easily accessible group. As it stands, I cannot view the asset post disposal (unless I have a record of the name, s/n, etc). Thanks!

**Comment by wilpig** [comment]
Use the log viewer and sort by the surplus action

First off, thanks for this great project!

I would like to request the ability to view previously disposed assets, similar to browsing the "storage room", but maybe also ordered by date. Sometimes we get requests like: "how many IBM servers were returned to lessors last year?". It would be helpful to be able to view these as a easily accessible group. As it stands, I cannot view the asset post disposal (unless I have a record of the name, s/n, etc). Thanks!

**Comment by sv3nster** [comment]
Thank you @wilpig. That works beautifully. One more issue since I have your ear. Does the update device templates button do anything for pre-imported devices? I am experiencing an issue similar to #439 and #960. I bulk imported several devices with half-completed templates. Later I go back and edit the templates by adding the port names, colors, notes. After using the update devices button, nothing changes. However, If I decrement the ports to zero, then revert the ports to their original amount, the correct template updates are displayed (without notes of course). Thanks, again!

**Comment by samilliken** [comment]
No, there is a report that I wrote specifically for this.    Go to the surplus/salvage report.   It spits out an excel spreadsheet, listed by date, and for the specific disposal method.
