### ISSUE TITLE
Custom attribute values too restricted

### ISSUE THREAD

**Issue by karipoulsen** [samilliken/openDCIM#1016]
I would like to see the custom attribute values not being filtered as heavily as they are now.

It should be possible to store double-quotes, for instance, allowing for XML and/or JSON encoded data. 

This would allow for database-level manipulation/selection for more complex data.

**Comment by wilpig** [comment]
<img width="586" alt="screenshot 2018-03-05 10 29 21" src="https://user-images.githubusercontent.com/1653882/36986695-14f3185c-2060-11e8-8ca4-6adb849bebdc.png">

As you included no examples I have included one of my own.
