### ISSUE TITLE
Rights check issue with vendor/mpdf/mpdf/ttfontdata

### ISSUE THREAD

**Issue by syndgr** [samilliken/openDCIM#1018]
Hello.

I'm setting up a test environment and have cloned openDCIM from git. When I run the install procedure, rightscheck.php suggests that vendor/mpdf/mpdf/ttfontdata should be writable but even with the directory chmod 777 it still doesn't like it.

![image](https://user-images.githubusercontent.com/20760738/37210111-7366077c-239f-11e8-8384-ed0bb8cad435.png)

``
> # ls -ld vendor/mpdf/mpdf/ttfontdata
> drwxrwxrwx 2 root root 4096 Mar  9 08:25 vendor/mpdf/mpdf/ttfontdata
``

**Comment by wilpig** [comment]
You have selinux or something installed and we can't detect that.  Not a bug, it's a local system problem.

**Comment by syndgr** [comment]
@wilbig Yes but it's disabled.

`# sestatus
SELinux status:                 disabled`

**Comment by wilpig** [comment]
It's a system level issue.   Apache is just reporting that it doesn't have permissions to write to that directory.  Climb up your directory tree and find the problem.  If you need to verify it by hand enable user 48 to have a login shell and go check it yourself as that user.
