### ISSUE TITLE
Don't build ldap DN by hands

### ISSUE THREAD

**Issue by paulignari** [samilliken/openDCIM#1023]
LDAP authentication in openDCIM manually creates the DN of the user's entry:

cn =% userid%, ou = users, dc = opendcim, dc = org

Please do not do it.
The DN can change (for example, when a user is moved from one OU to another).
Multiple subtrees can be used to store users, and it is not possible to know which user belongs to only by their username, etc.

The right method to perform LDAP authentication is:

* connect to the LDAP server anonymously or with a service account
* search for the entry with the uid (or any other unique attribute you use for authentication, maybe email) equal to the string provided by the user
* use the DN of that entry and the user's password to bind the LDAP server as the user
* if the last binding is successful, the user is authenticated.

**Comment by wilpig** [comment]
Good suggestion, looking forward to your pull request.
