### ISSUE TITLE
Lines in cabinet view are OFF - How to remove or sync them?

### ISSUE THREAD

**Issue by buomque** [samilliken/openDCIM#1025]
Hi all,

Is there a way to either remove those lines or sync them correctly in cabinet view?

![untitled](https://user-images.githubusercontent.com/10902128/38167920-1c5368e2-34f4-11e8-87ee-7d2e508f6c18.png)

Thank you,

**Comment by wilpig** [comment]
Browser version?  Opendcim version?   Is this happening on https://dev.opendcim.org ?  have you ever filed a bug report before ?

**Comment by buomque** [comment]
Hi Wilpig,

I am using Chrome (newest version). It works fine in IE.

my OpenDCIM is 18.01.

I haven't filed a bug before as I am totally new to OpenDCIM and this forum.

Thank you for the reply,

**Comment by wilpig** [comment]
<img width="1384" alt="screenshot 2018-03-31 17 11 10" src="https://user-images.githubusercontent.com/1653882/38168002-8d893b88-3506-11e8-80cd-2e2d3e5334d3.png">
Newest chrome, and v18.01.  I don't see an issue.

**Comment by wilpig** [comment]
I managed to recreate your bug by using the in browser zoom function.  The fix is to reset your zoom so it displays the page correctly.

**Comment by wilpig** [comment]
You have a font or something in your set up that is off from the standard that is causing it.  I cannot tell you what it is but I clicked on the menu and when I changed the zoom it was messed up.  At 100% it was normal, there is something in your system that is off.

**Comment by buomque** [comment]
I think it's issue with my Windows resolution.

It is good now. Thank you very much!
