### ISSUE TITLE
Zone assignment for cabinets is blanking out in the UI

### ISSUE THREAD

**Issue by samilliken** [samilliken/openDCIM#1029]

**Comment by wilpig** [comment]
already fixed this morning.

**Comment by wilpig** [comment]
https://github.com/samilliken/openDCIM/commit/c5e5171b47fb6c2f17f58c4377e6f8a63abb2217

**Comment by samilliken** [comment]
Yes, well, you didn't create an issue for it.   I need issues created since
that's what I go back to look at for the CHANGELOG, and it's also what we
tell people to check before submitting a new issue.

Scott
