### ISSUE TITLE
Uncaught TypeError: Cannot read property 'Front' of undefined

### ISSUE THREAD

**Issue by r1chy** [samilliken/openDCIM#1031]
Hey, guys,

I updated openDCIM from version 4.5 to 18.01 and did everything right.
When I now select my DataCenter, this error appears in the browser console,
```
Uncaught TypeError: Cannot read property 'Front' of undefined
    at getPic (common.js:1637)
    at InsertDevice (common.js:1672)
    at Object.<anonymous> (common.js:1353)
    at j (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
    at x (jquery.min.js:4)
    at XMLHttpRequest.b (jquery.min.js:4)
```

And I don't have any pictures that show up at the rack.
![image](https://user-images.githubusercontent.com/13568337/38816822-3f0aa1ca-4197-11e8-9850-f467adbaba0d.png)

But when I search for my system, I find it.
![image](https://user-images.githubusercontent.com/13568337/38816887-64a92c4e-4197-11e8-9440-02a20e76ed4c.png)
and all information about the system is also available, e.g. all user-defined attributes are correctly filled in.
Does anyone have the same problem? 
Thanks in advance

**Comment by wilpig** [comment]
This is not a bug report, use the mailing list to find out how to rebuild your image cache which clearly didn't build correctly during the upgrade.
