### ISSUE TITLE
Display Row without cabinet

### ISSUE THREAD

**Issue by newargus** [samilliken/openDCIM#1035]
Error on trying to display rowview.php when no cabinets linked. to the row.

On line 76, 
$dcID=$cabinets[0]->DataCenterID;

Why not directly use instead:
$dcID=$cabrow->DataCenterID;

**Comment by mullaneywt** [comment]
Could not reproduce this issue in version 19.01.

If @newargus is still around and happens to be be able to still be able to produce this, can he or she update?  Otherwise it looks like this is resolved.
