### ISSUE TITLE
create.sql script fails on Ubuntu 16.0.4 with MySQL 5.7

### ISSUE THREAD

**Issue by matthewalr** [samilliken/openDCIM#1038]
The varchar values set for several tables are too large and exceed the maximum total size of 65535 for all columns in a table. The tables with issues are fac_DeviceCustomAttributes, fac_DeviceTemplateCustomValue, fac_DeviceCustomValue. Lowering the varchar value to ~20000 seems to resolve the issue, but not sure about the implications to changing this value. Here is the error:

ERROR 1074 (42000) at line 912: Column length too big for column 'DefaultValue' (max = 21845); use BLOB or TEXT instead

[create.zip](https://github.com/samilliken/openDCIM/files/2006726/create.zip)

**Comment by wilpig** [comment]
If you follow the install instructions you will get the length auto-adjusting based on the max row length as designed.  The maximum size of a varchar is 65535 but it can only expand to the max available for the row minus the other columns.   I have built an ubuntu 16.04 test bed and installed successfully with the existing sql.  Odds are high that you have strict transactions enabled, which they are by default with that version, and it causes all kinds of kooky behaviors.  #457 
```
mysql> describe fac_DeviceCustomValue;
+-------------+------------+------+-----+---------+-------+
| Field       | Type       | Null | Key | Default | Extra |
+-------------+------------+------+-----+---------+-------+
| DeviceID    | int(11)    | NO   | PRI | NULL    |       |
| AttributeID | int(11)    | NO   | PRI | NULL    |       |
| Value       | mediumtext | YES  |     | NULL    |       |
+-------------+------------+------+-----+---------+-------+
3 rows in set (0.00 sec)
```
