### ISSUE TITLE
Search/Export Report Does Not Show Devices with No Template Assigned

### ISSUE THREAD

**Issue by samilliken** [samilliken/openDCIM#1042]
Going to simplify this up a bit in the process.    Easy to confirm, though - create a device with no template, then run the search/export.   It won't be in the list.

This report is scheduled to be redone as an Excel output, but for now, need to at least get the data accurate.

**Comment by wilpig** [comment]
No, that should stay as data tables.  It is a search and NOT just a report.

**Comment by samilliken** [comment]
Then it can become "search_dc.php" instead of search_export.php.

**Comment by wilpig** [comment]
The datatables offers the export functionality.  Us shifting to one or the other is not the best move here and maintaining the same information in two different places just for excel is stupid.

**Comment by wilpig** [comment]
[DC 1-A export.xlsx](https://github.com/samilliken/openDCIM/files/2053799/DC.1-A.export.xlsx)
Being able to filter the results and get a spreadsheet of that subset is beneficial.
