### ISSUE TITLE
UTF8 again

### ISSUE THREAD

**Issue by Negatifff** [samilliken/openDCIM#1054]
Good day.

I'm russian and my english not perfect, sorry. Try to explain :)

In opendcim 18.01 I have some cabinets with some servers on each. All work, all fine. But... When I add server with label on russian lang - cabinet stop loading after reload page with error: 

Slim Application Error

The application could not run because of the following error:
Details
Type: ErrorException
Code: 2
Message: json_encode(): Invalid UTF-8 sequence in argument
File: /var/www/html/dcim-18.01/api/v1/index.php
Line: 83
Trace

#0 [internal function]: Slim\Slim::handleErrors(2, 'json_encode(): ...', '/var/www/html/d...', 83, Array)
#1 /var/www/html/dcim-18.01/api/v1/index.php(83): json_encode(Array)
#2 /var/www/html/dcim-18.01/api/v1/getRoutes.php(274): echoResponse(Array)
#3 [internal function]: {closure}('5')
#4 /var/www/html/dcim-18.01/vendor/slim/slim/Slim/Route.php(468): call_user_func_array(Object(Closure), Array)
#5 /var/www/html/dcim-18.01/vendor/slim/slim/Slim/Slim.php(1355): Slim\Route->dispatch()
#6 /var/www/html/dcim-18.01/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()
#7 /var/www/html/dcim-18.01/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
#8 /var/www/html/dcim-18.01/vendor/slim/slim/Slim/Middleware/PrettyExceptions.php(67): Slim\Middleware\MethodOverride->call()
#9 /var/www/html/dcim-18.01/vendor/slim/slim/Slim/Slim.php(1300): Slim\Middleware\PrettyExceptions->call()
#10 /var/www/html/dcim-18.01/api/v1/index.php(187): Slim\Slim->run()
#11 {main}

When I rename server from cyrillic label to latin - all work fine again.
When I editing this server - all cyrillic labels shows right, w/o nonprint symbols.

My database created with utf8 codepage and all tables created with utf8 codepage (like in create.sql).

any help?

**Comment by wilpig** [comment]
Put an example server name here that I can copy into one of our development instances for troubleshooting.

**Comment by Negatifff** [comment]
i used "Полка под сервер"

**Comment by wilpig** [comment]
https://dev.opendcim.org/cabnavigator.php?cabinetid=100

login: dcim
pass: dcim

**Comment by wilpig** [comment]
Check to make sure this is how you entered it.  If so I am going to guess that i've already corrected this in the javascript and it will be in the next release.

**Comment by Negatifff** [comment]
Yep, server name is correct and showing right.
Thanks, waiting new release.
