### ISSUE TITLE
CDU Label cleared after update

### ISSUE THREAD

**Issue by OddmarDam** [samilliken/openDCIM#1060]
When i add a CDU device in a rack and hit update. The Label disappears after the save.
Then, if i update information on the page and hit update again, the required field validator kicks in with an error.
Also the template goes away.

![image](https://user-images.githubusercontent.com/4441007/42887781-a5aed310-8a9e-11e8-903a-7dea1a702caa.png)

**Comment by wilpig** [comment]
what was the name of the device that you were trying to add?

**Comment by OddmarDam** [comment]
Just any generic name.

**Comment by wilpig** [comment]
Try it at https://dev.opendcim.org  and see if the issue is still present or if it has possibly been corrected from some of the translation related javascript corrections.

**Comment by wilpig** [comment]
Unable to reproduce.  https://dev.opendcim.org/devices.php?DeviceID=5130

**Comment by OddmarDam** [comment]
I went to dev.opendcim.org and created a new power panel. Service stopped working :(
That is the same that i see on my local install.

I tried rebooting my server. No help

**Comment by OddmarDam** [comment]
![image](https://user-images.githubusercontent.com/4441007/42895702-92b729b0-8ab2-11e8-9ab9-fb2a2ce3b85a.png)

**Comment by wilpig** [comment]
I see you created power panel 14 and there is now an error.  I will look into that.  You reported errors with creating CDUs though.

**Comment by OddmarDam** [comment]
Yes, i realize that the error might occur when i was working with the power panels

**Comment by wilpig** [comment]
Try the dev instance now.

**Comment by OddmarDam** [comment]
Yes, works now.

How do i get the newest version ?

**Comment by wilpig** [comment]
Click the link labeled "Potential fix for #1060" and make that code change to your server.  I need to test this more to see what other things this might affect.  It appears to be cosmetic and just related to the gauges but I need to do more testing later.

**Comment by dmbanke** [comment]
@wilpig I have also tried the code change. The Label and Template no longer clear. On 0 height CDUs the Device Images section now shows on the Data Center Device Detail page however.

**Comment by dmbanke** [comment]
In further testing without the change applied you can reproduce the issue on the Demo site. I did it today in the Test CDU cabinet A01. If someone takes a horizontal CDU and changes it to an Appliance, saves it, then changes it back to a CDU the Label and Template no longer show. Not sure why anyone would do this BUT...
