### ISSUE TITLE
Audit date request

### ISSUE THREAD

**Issue by pgriego** [samilliken/openDCIM#1067]
Would it be possible to get the last time a device was audited column included in the Search/Export by Data Center report? Or a report created in the Audit Reports section to give that detail. The issue is wanting a report that will show what devices have been audited, haven't been audited, and when they were last audited. The actions log can give us the most of what we need, however, it doesn't give what hasn't been audited.  Thank You.

**Comment by wilpig** [comment]
I don't see that as something that we would want to add to the export but you can.  https://github.com/samilliken/openDCIM/blob/master/search_export.php#L37  You will want to add AuditStamp to this list here like b.AuditStamp and then add it to the headers https://github.com/samilliken/openDCIM/blob/master/search_export.php#L55 for the table, and finally add it to the output for the spreadsheet https://github.com/samilliken/openDCIM/blob/master/search_export.php#L106
