### ISSUE TITLE
PHP Warning:  Illegal string offset in search.php/misc.inc.php

### ISSUE THREAD

**Issue by christoph2014** [samilliken/openDCIM#1079]
I have a problem with the search feature of openDCIM after upgrading from v4.3.1 to v18.01.

While using search, the cabinets are no more visible in the results. Instead of its names there is only the id. Besides there are some php warnings in the error.log of apache2.

> [Tue Sep 04 08:15:26.329097 2018] [php7:warn] [pid 23367] [client xxx.xxx.xxx.xxx:xxxxx] PHP Warning:  Illegal string offset 'name' in /var/www/openDCIM-18.01/search.php on line 240, referer: https://xxx.xxx.xxx.xxx/opendcim/search.php
[Tue Sep 04 08:15:26.329315 2018] [php7:warn] [pid 23367] [client xxx.xxx.xxx.xxx:xxxxx] PHP Warning:  Illegal string offset 'dc' in /var/www/openDCIM-18.01/search.php on line 241, referer: https://xxx.xxx.xxx.xxx/opendcim/search.php
[Tue Sep 04 08:15:26.329554 2018] [php7:warn] [pid 23367] [client xxx.xxx.xxx.xxx:xxxxx] PHP Warning:  Illegal string offset 'name' in /var/www/openDCIM-18.01/misc.inc.php on line 184, referer: https://xxx.xxx.xxx.xxx/opendcim/search.php
[Tue Sep 04 08:15:26.330361 2018] [php7:warn] [pid 23367] [client xxx.xxx.xxx.xxx:xxxxx] PHP Warning:  Illegal string offset 'dc' in /var/www/openDCIM-18.01/search.php on line 444, referer: https://xxx.xxx.xxx.xxx/opendcim/search.php
[Tue Sep 04 08:15:26.330450 2018] [php7:warn] [pid 23367] [client xxx.xxx.xxx.xxx:xxxxx] PHP Warning:  Illegal string offset 'name' in /var/www/openDCIM-18.01/search.php on line 445, referer: https://xxx.xxx.xxx.xxx/opendcim/search.php

My environment:
Ubuntu 18.04.1
Apache2 2.4.29
PHP 7.2
openDCIM 18.01

**Comment by wilpig** [comment]
Those warning show that something with the sql query didn't complete correctly.  We don't do troubleshooting on github, take it to the mailing list.  I would suspect that something with your upgrade didn't completely correctly and I would restore the database and let it run again.

**Comment by christoph2014** [comment]
I just identified the problem and fixed it to work in my environment.
Obviously $cabtemp[$key] was not handled as an array. After initializing it works just like expected.
Below is the customized code snippet of search.php line 235-247.

`if($key>0){`
`                        $cab->Location='dc lookup error';`
`                        $cab->DataCenterID='0';`
`                        $cab->CabinetID=$key;`
`                        if($cab->GetCabinet()){`
`                                $cabtemp[$key]=array();`
`                                $cabtemp[$key]['name']=$cab->Location;`
`                                $cabtemp[$key]['dc']=$cab->DataCenterID;`
`                                $dctemp[$cab->DataCenterID]=''; // Add datacenter id to list for loop`
`                        }else{`
`                                unset($cabtemp[$key]);`
`                        }`
`                } elseif( $key=="-1" ) {`
