### ISSUE TITLE
  Undefined variable: dbport in openDCIM-18.02/db.inc.php

### ISSUE THREAD

**Issue by pentiumoverdrive** [samilliken/openDCIM#1088]
in v18.02, it looks like the database port is not defined in db.inc.php:

PHP Notice:  Undefined variable: dbport in openDCIM-18.02/db.inc.php on line 27, referer: configuration.php

Database connections works fine anyway, at least when using default 3306 port.

**Comment by wilpig** [comment]
Already patched.
https://github.com/samilliken/openDCIM/pull/1087
