### ISSUE TITLE
Installation with LDAP Default Authentication

### ISSUE THREAD

**Issue by valmison** [samilliken/openDCIM#1091]
Before running OpenDCIM 18.02 for the first time, I edited the **db.inc.php** script with parameters for DB access and **AUTHENTICATION** for **LDAP**, but an error occurred during the execution of the **install.php** script and the installation stopped. Google Chrome displays the **ERR_TOO_MANY_REDIRECTS** message.

I am performing an initial installation and not an OpenDCIM version update. In this case, the database does not have tables, however, after the execution error of the install.php script, the database is configured with the default tables and data.

I believe the problem is due to the redirection performed by the command loaded inside an <iframe> like similar problems I found in Internet articles. I noticed that during the execution of the **install.php** script require_once of **preflight.php** is executed, which loads the **preflight.inc.php** script inside an **_<iframe>_**, which in turn executes the command **_header("Location": ldap_bootstrap .php ")_** constant on line 169, provided that AUTHENTICATION is set to LDAP.

I'm trying to find a solution to the problem, but in the meantime I'd like to share it.

**Comment by wilpig** [comment]
I'll look into it.  In the meantime to install I would set the authentication to apache.

**Comment by valmison** [comment]
> I'll look into it. In the meantime to install I would set the authentication to apache.

Thanks for the feedback.

**Comment by wilpig** [comment]
This will be fixed with 18.03, we're going to remove the ldap installation option but include an .htaccess example with a preset user/pass combination of dcim/dcim  or admin/admin

**Comment by valmison** [comment]
I performed a test by replacing the require_once from preflight.php to preflight.inc.php in install.php and it worked correctly.

You would like to receive a pull request with a customization for ldap authentication.

> This will be fixed with 18.03, we're going to remove the ldap installation option but include an .htaccess example with a preset user/pass combination of dcim/dcim or admin/admin. LDAP authentication will still work as well as saml, oauth, etc but you will have to configure it after the installation is complete.

I performed a test by replacing the require_once from preflight.php to preflight.inc.php in install.php and it worked correctly.

You would like to receive a pull request with a customization for ldap authentication.

**Comment by wilpig** [comment]
That would work because that was the old functionality.  We have decided on a path forward as I described, I didn't close this issue because we will be committing the changes to this.

**Comment by samilliken** [comment]
This is now mitigated with the LDAP_Debug_Password implementation, which allows an override password while you setup the actual DNs.
