### ISSUE TITLE
Bulk devices import  failed 

### ISSUE THREAD

**Issue by vinod-wagh** [samilliken/openDCIM#1095]
Bulk import failed in opendcim 18.01

![bulk device import failed](https://user-images.githubusercontent.com/12002542/47702594-72199980-dc43-11e8-82cf-3becedbefe1a.png)

**Comment by samilliken** [comment]
Please don't open new issues for things that have been answered repeatedly on the mailing list.

You have a blank line being passed in your Excel file.   Excel is simply an idiot about this at times.   Export your file to .CSV, make sure there are no blank lines at the end, and import that into openDCIM.
