### ISSUE TITLE
Switch ports status not working

### ISSUE THREAD

**Issue by WoMec** [samilliken/openDCIM#1096]
Hi, after update from 18.01 to 18.02, all ports on all switches are down. Other pooling works fine (notes, port names etc.) only port status has stoped working.

**Comment by maverickdb** [comment]
Same here, we updated from 4.5 to 18.02

Error_log:

==> /var/log/httpd/error_log <==
[Tue Nov 13 11:10:35.751703 2018] [:error] [pid 18646] [client 192.168.10.41:42606] PHP Notice:  Undefined index: NetworkCapacityReportOptOut in /var/www/html/opendcim/devices.php on line 503, referer: https://opendcim/devices.php?DeviceID=34

@WoMec , I replaced this function code with the previous version and it works again.

**Comment by wilpig** [comment]
#1086   This was corrected for 18.03

**Comment by WoMec** [comment]
Perfect, it works again :) Thank you

**Comment by mksharifinia** [comment]
hello 
this address is down:
https://opendcim/devices.php?DeviceID=34

please!

**Comment by wilpig** [comment]
That address never worked, it would only work in your environment if you have a host defined as opendcim in whatever your search strings are.

**Comment by mksharifinia** [comment]
port status of switch don't show ! 

What should I do?
