### ISSUE TITLE
Enhancement - Add 3 device fields

### ISSUE THREAD

**Issue by ekrichbaum** [samilliken/openDCIM#1113]
Add Software Version, Purchase Price, and ReplacementCost directly to Device class rather than using custom fields.

72,74d71
<       var $SoftwareVer;
<       var $PurchasePrice;
<       var $ReplacementCost;
148,150d144
<               $this->SoftwareVer=sanitize($this->SoftwareVer);
<               $this->PurchasePrice=sanitize($this->PurchasePrice);
<               $this->ReplacementCost=sanitize($this->ReplacementCost);
168,170d161
<               $this->SoftwareVer=stripslashes($this->SoftwareVer);
<               $this->PurchasePrice=stripslashes($this->PurchasePrice);
<               $this->ReplacementCost=stripslashes($this->ReplacementCost);
223,225d213
<               $dev->SoftwareVer=$dbRow["SoftwareVer"];
<               $dev->PurchasePrice=$dbRow["PurchasePrice"];
<               $dev->ReplacementCost=$dbRow["ReplacementCost"];
423,424d410
<                       SoftwareVer=\"$this->SoftwareVer\", PurchasePrice=\"$this->PurchasePrice\", 
<                       ReplacementCost=\"$this->ReplacementCost\",
795,796d780
<                       SoftwareVer=\"$this->SoftwareVer\", PurchasePrice=\"$this->PurchasePrice\", 
<                       ReplacementCost=\"$this->ReplacementCost\",

ALTER TABLE fac_Device
ADD COLUMN SoftwareVer VARCHAR(80) AFTER InstallDate,
ADD COLUMN PurchasePrice VARCHAR(15) AFTER SoftwareVer,
ADD COLUMN ReplacementCost VARCHAR(15) AFTER PurchasePrice;

And display in devices.php.  Allows for reporting, searching, audit reports showing vulnerable or outdated software or a bugged version and the like.

1744,1755d1743
<                  <div><label for="SoftwareVer">'.__("Software Version").'</label></div>
<                  <div><input type="text" name="SoftwareVer" id="SoftwareVer" value="'.$dev->SoftwareVer.'"></div>
<               </div>
<               <div>
<                  <div><label for="PurchasePrice">'.__("Purchase Price").'</label></div>
<                  <div><input type="text" name="PurchasePrice" id="PurchasePrice" value="'.$dev->PurchasePrice.'"></div>
<               </div>
<               <div>
<                  <div><label for="ReplacementCost">'.__("Replacement Cost").'</label></div>
<                  <div><input type="text" name="ReplacementCost" id="ReplacementCost" value="'.$dev->ReplacementCost.'"></div>
<               </div>
<               <div>

**Comment by samilliken** [comment]
While I appreciate the effort, it's misplaced.   Any time fields are added to the Device structure, there are many more places it has to be propagated.

You can already search by custom fields, and several reports also include custom fields in them.

**Comment by ekrichbaum** [comment]
ok.  I had download the release code and that didn't seem to be the case.  I'll look again. Install did not go smoothly (first created user had no username dumped to db, had to add directly in database to login) under Fedora as a base.

Visualization, etc. is nice and looks better than Racktables. Quite a few things aren't working well though so may just have to fork. With a handful of changes like this, it served our desires pretty well. Is there a reason you wouldn't extend the base schema for items that would always be there?

**Comment by wilpig** [comment]
Because he already told you there is no reason to extend it.  The custom attributes do just that, and you can export them from the premade reports or you can build your own reports.  It makes no sense to require those fields for people that do not need them when you can add them with ease.
