### ISSUE TITLE
ldap using 'cn', which is Common Name..

### ISSUE THREAD

**Issue by ThomasADavis** [samilliken/openDCIM#1114]
I found that in upgrading to 18.2, ldap stopped working for me.

It's using 'cn' attribute in the login_ldap.php, which is common name, which according to the ldapwiki:

https://ldapwiki.com/wiki/Cn

```If the object corresponds to a person, it is typically the person's full name.```

We do not use 'cn' names for groups, we use 'uid' for groups, along with memberUid.

Changing to use 'uid' works.  

Time for another LDAP config parameter?

**Comment by samilliken** [comment]
It's already user defined in the configuration screen.

**Comment by ThomasADavis** [comment]
No, it's not.

Look at line 146 in login_ldap.php

$found_dn=@$ldapResults[0]['cn'][0];

For a ldap instance using rfc2307, this does not work.

**Comment by wilpig** [comment]
It really isn't used.  I use (|(userprincipalname=%userid%)(cn=%userid%)) as my base search and i'm matching on the princpalname in my search string.  You just need to use a better search string.

`$found_dn=@$ldapResults[0]['cn'][0];
              $ldapSearchDN=str_replace("%userid%",$found_dn,html_entity_decode($config->ParameterArray['LDAPBaseSearch']));`

**Comment by ThomasADavis** [comment]
We do not use 'CN' here in rfc2307 groups, it's uid.

(&(objectClass=posixGroup)(memberUid=%userid%))

**Comment by ThomasADavis** [comment]
Fails.

**Comment by ThomasADavis** [comment]
group searches is what is broken. 

                                $ldapSearchDN=str_replace("%userid%",$found_dn,html_entity_decode($config->ParameterArray['LDAPBaseSearch']));

so, no, what your propose does not change the fact it's using CN and not uid.

so stop posting stupid answers.

**Comment by wilpig** [comment]
<img width="490" alt="screenshot 2018-12-27 13 05 07" src="https://user-images.githubusercontent.com/1653882/50491453-10be3e80-09d8-11e9-9dde-b074ab3f4861.png">
Assuming this is the full extent of your user object the problem you are experiencing is that your user object isn't presenting the list of groups it is a member of and that is how the code is searching.

```    function checkAccess($ldapobject){
        $config=new Config();
        $access=false;
        if(array_key_exists("memberof",$ldapobject)){
            foreach ($ldapobject['memberof'] as $group){
                if(!strcasecmp($group, $config->ParameterArray['LDAPSiteAccess'])){
                    $access=true;
                }
            }
        }else{
            if(!strcasecmp($ldapobject['dn'], $config->ParameterArray['LDAPSiteAccess'])){
                $access=true;
            }
        }
        return $access;
    

} 
```

<img width="512" alt="screenshot 2018-12-27 13 06 32" src="https://user-images.githubusercontent.com/1653882/50491501-419e7380-09d8-11e9-98af-e67499237d11.png">

Having an actual understanding of the code I can again say that point where CN is listed is essentially useless and does next to nothing.  What you are suggesting whether you realize it or not is that we need to pull the list of users from each group and then check for membership on a per user basis or you're missing information from the ldap search.

**Comment by samilliken** [comment]
Please submit a working pull request.   As I have stated countless times before - I don't know LDAP and barely got this to work with the example I managed to steal from the Google.    However, if you simply want to tell me that we're doing it wrong, that's not productive.    Working pull requests are welcome.

**Comment by ThomasADavis** [comment]
It's now obvious that Pig does not understand LDAP rfc2307 either.

Group membership is a separate object from the user object in rfc2307, and membership is denoted using uid or the uid object (rfc2307 vs rfc2307bis).

so using 'cn' to search for group membership in a rfc2307 schema fails.

And no, I was not going to post the complete object in a public forum.

**Comment by wilpig** [comment]
I understand ldap and have worked with it for nearly 20 years. I'm not bothering quoting RFCs, i'm posting the actual code and how it is working.  It isn't using the CN for searching for groups it searching for the memberof attribute or the nested DN attribute for people using openldap.  I posted the actual loop that is determining group membership.

**Comment by ThomasADavis** [comment]
```				// These are standard schema items, so they aren't configurable
				// However, suppress any errors that may crop up from not finding them
				$found_dn=@$ldapResults[0]['cn'][0];
				$ldapSearchDN=str_replace("%userid%",$found_dn,html_entity_decode($config->ParameterArray['LDAPBaseSearch']));
				$ldapSearch=ldap_search($ldapConn,$config->ParameterArray['LDAPBaseDN'],$ldapSearchDN);
				$ldapResults=ldap_get_entries($ldapConn,$ldapSearch);
```

this code has a hard-coded 'cn' in it, so it assumes activedirectory type member

**Comment by ThomasADavis** [comment]
> I understand ldap and have worked with it for nearly 20 years. I'm not bothering quoting RFCs, i'm posting the actual code and how it is working. It isn't using the CN for searching for groups it searching for the memberof attribute or the nested DN attribute for people using openldap. I posted the actual loop that is determining group membership.

and when the group search fails, that loop will return nothing, because it's searching for groups based on CN, not UID in a rfc2307 schema.

**Comment by wilpig** [comment]
By adding in an error log statement at https://github.com/samilliken/openDCIM/blob/master/login_ldap.php#L148  of something to the effect of error_log($ldapSearchDN);

Then again another to show the contents of $config->ParameterArray['LDAPBaseDN'] we can take those values and throw them into the following search against AD from the values that I have said will work at this point in the code where CN is essentially doing nothing.

[wilbur@hosting7 openDCIM]$ ldapsearch -x -b "DC=ad,DC=wilpig,DC=org" -D "tablesb@ad.wilpig.org" -h 10.0.0.243 -W '(|(userprincipalname=Limited User)(cn=Limited User))'

The CN value was pulled from an earlier ldap search so that we are just now matching again against a known value that was pulled from ldap and this time around we are looking for the memberof statements.

This is NOT searching for groups based on CN it is actually attempting to just lookup the same object htat we already loaded again because we love to do things repeatedly.  So while you are harping on a CN value it actually does nothing.  that entire section can be removed and have no real issues.  

Stop quoting me RFC and read the god damned code.

**Comment by ThomasADavis** [comment]
1st, we do not have anything like you posted, open your damn eyes.

2nd, the ldapresults are over written  in the else statement, that then calls an for loop, that then calls the checkaccess

read the GD code your self.  Start at line 128, and not that ldapResults are overwritten at line 150.

**Comment by wilpig** [comment]
Remove lines 144: 150 in your codebase.

**Comment by wilpig** [comment]
Defined Attributes for RFC2307
https://tools.ietf.org/html/rfc2307#section-2.2

Additionally, some of the attributes defined in [[RFC2256](https://tools.ietf.org/html/rfc2256)] are required.

> 5.4. cn
>    This is the X.500 commonName attribute, which contains a name of an
>    object.  If the object corresponds to a person, it is typically the
>    person's full name.
>     ( 2.5.4.3 NAME 'cn' SUP name )

Further down the hole for rfc2307 we find what are the requirements for group membership. https://tools.ietf.org/html/rfc2307#section-5.3

>    The account object class provides a convenient structural class for
>    posixAccount, and SHOULD be used where additional attributes are not
>    required.

For your RFC comments in this case CN is required.

**Comment by wilpig** [comment]
Fix your schema

**Comment by ThomasADavis** [comment]
Our schema already has a 'cn' attribute in the userobject.

You are the clueless one.  Look up groups under RFC2307.  They do NOT use 'cn', they use either member, memberOf, or memberUid.  These are NOT attached to the userObject at all.

This is NOT active directory.  This is openldap running a RFC2307 schema.

**Comment by wilpig** [comment]
The section of code you are looking at is pulling a user object.  NOT a group.
