### ISSUE TITLE
Stop requiring logo.png to be in /images/

### ISSUE THREAD

**Issue by samilliken** [samilliken/openDCIM#1133]
Since we're allowing that file to be replaced, it should be allowed to reside anywhere - not just in /images/.

**Comment by asohh** [comment]
to ensure the old installations still work after the update, the following line should be added to the file for the db update:

UPDATE fac_Config set Value=concat("images/",Value) WHERE Parameter="PDFLogoFile";

**Comment by samilliken** [comment]
This already works
