### ISSUE TITLE
report audit frequency  without information

### ISSUE THREAD

**Issue by LaurentBrexel** [samilliken/openDCIM#1135]

**Comment by LaurentBrexel** [comment]
report_audit_frequency.php don't give any information.

I think it's due to a sql request in this php program witch refer to fac_Users table instead of fac_People...

Thanks to solve this issue !

Regards,

Laurent.

**Comment by wilpig** [comment]
Problem was already corrected and the fix is present in the latest release of 19.01.

https://github.com/samilliken/openDCIM/commit/c59c59094818007ca2c764018b5124c1ed0af17c#diff-f35243d9d2523b3b0ae14c057882a01a

https://github.com/samilliken/openDCIM/blob/master/report_audit_frequency.php#L260
