### ISSUE TITLE
search fonction failed at line 163

### ISSUE THREAD

**Issue by twotty** [samilliken/openDCIM#1141]
Hi,
When I use search fonction, I have an error on search.php at line 163.
I think there is a syntax error on this line. When I use this, all it's good : 
$cabtemp[$device->Cabinet] = "";
Original :
$cabtemp[$device->Cabinet] = [];

Can you check if it good and update code ?
Thank and regards

**Comment by wilpig** [comment]
You have no information here about what version you are using, what php version, etc

**Comment by twotty** [comment]
Sorry, I'm in PHP 5.3.3 and Opendcim 19.01.

**Comment by mullaneywt** [comment]
This is likely due to the php issue.  See also issue 1160
