### ISSUE TITLE
Dose not operate Cabinetnevergae.php.

### ISSUE THREAD

**Issue by xizon05** [samilliken/openDCIM#1142]
Hi, Dear

I have an error on cabnetnevigator.php.

I can not add on device to cabniet.

-------------- Acces.log -----------------------------------
192.168.125.1 - dcim [22/Mar/2019:15:25:05 +0900] "GET /api/v1/device?Cabinet=5 HTTP/1.1" 500 2302 "https://192.168.125.136/cabnavigator.php?cabinetid=5" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.183 Safari/537.36 Vivaldi/1.96.1147.55"
------------------------------------------------------------

"/api/v1/device" File dose not exists.

Can you give me good advice?

Thank and regards.

Apache 2.2.15/PHP 5.3.3 and Opendcim 19.01
I've try on Vivaldi/1.96.1147.55

**Comment by wilpig** [comment]
This is a server configuration issue, please direct all support questions to the mailing list.

Close #1142
