### ISSUE TITLE
Hi Scott,

### ISSUE THREAD

**Issue by xizon05** [samilliken/openDCIM#1143]
Hi Scott,

The "Rebuild Image Cache" meter hits a 100% now, but still I don't see my devices on the cab cabnavigator. Though I can successfully add devices, and am able to see them in MySQL and even on the cabinet preview to choose a unit position, when I add new device.  -  ↡Screenshots↡
 
Please let me know if you need me to run other tests for better clarification of the issue.

The API test also returns the following, and I assume it should be normal based on the answers on other threads;
> {"error":false,"errorcode":200}

![image](https://user-images.githubusercontent.com/42277625/44058316-9ce1579e-9f02-11e8-9a7f-75622f77f3b2.png)

![image](https://user-images.githubusercontent.com/42277625/44058301-955d9eba-9f02-11e8-9669-d735e1bdc31f.png)

Thank you.

_Originally posted by @AhmadMansoorSajid in https://github.com/samilliken/openDCIM/issues/1066#issuecomment-412666107_

**Comment by xizon05** [comment]
Are you solve those issue?

**Comment by samilliken** [comment]
Per instructions at https://opendcim.org/support.html you need to check the mailing list.    GitHub issues is not a question forum, it's an actual issue tracking area.
