### ISSUE TITLE
My opendcim shows only report menu

### ISSUE THREAD

**Issue by JL07** [samilliken/openDCIM#1144]
![opendcim](https://user-images.githubusercontent.com/33813754/54990335-bf175700-4fba-11e9-96d4-8489c680be42.png)

Hello guys,

I can't handle my openDCIM, because it's just shows a report menu...

Can someone help me please?

**Comment by samilliken** [comment]
This has been answered numerous times on the mailing list.   GitHub is for actual issue tracking, not user questions.   Direct all questions to the mailing list per the FAQ and Website instructions.
