### ISSUE TITLE
SiteAdmin still has Contact Management Rights

### ISSUE THREAD

**Issue by samilliken** [samilliken/openDCIM#1147]
We fixed the Deparment editing to require the (not really) new attribute of "Manage Contacts and Departments" but didn't fix the usermgr.php file.

**Comment by wilpig** [comment]
We don't have any controls in place to prevent a condition where nobody has the contact manager right, this was always the other condition to allow that.  I know we discussed changing this a while back to allow a user to admin the site without having access to everything else but I think the site admin should still be considered nearly god mode as a safety

**Comment by samilliken** [comment]
Going to reopen this as our discussion on IRC has led to the realization that we need another level of rights - a System Admin that can manage the Site Configuration and also has inherited all other rights.

**Comment by samilliken** [comment]
Stale issue as there has been no discussion on it for over a year.
