### ISSUE TITLE
LDAP installation API permits anonymous read

### ISSUE THREAD

**Issue by FliesLikeABrick** [samilliken/openDCIM#1148]
Present in at least versions 18.01 and 19.01

https://www.opendcim.org/demo/api/v1/device

The list of devices and other objects can be retrieved with no auth token or HTTP cookie provided.  Not all data is visible, but devices, cabinets, and probably facilities are accessible.

Not all fields are accessible, but most objects themselves are enumerable, such as people:
https://www.opendcim.org/demo/api/v1/people

**Comment by timlegge** [comment]
@wilpig @samilliken I have been looking at this as a user wondered why the api call results differed from authenticated results.

I found that while the index.php checked to ensure that the UserID and APIKey matched it returned the information anyway.  If UserID was provided in the header it had read rights to the information it did not matter whether the APIKey matched it would retrieve all the information

I can make $valid a global variable and check whether the it is true for each of the get requests but that is unlikely to be optimal.

It appears from reading the comments that the valid UserID to APIKey match should be required for any api request.  Is that still true?  As it is, it does not work that way but I am unsure of the best way to sort that out.

**Comment by timlegge** [comment]
Actually the fix is:

```diff --git a/api/v1/index.php b/api/v1/index.php
index 9c77e801..37e289cd 100644
--- a/api/v1/index.php
+++ b/api/v1/index.php
@@ -137,7 +137,6 @@ $app->hook( 'slim.before.dispatch', function() use($person) {
                $headers = apache_request_headers();
                $response = array();
                $app = \Slim\Slim::getInstance();
-
                $valid = false;
 
                if ( isset( $_SESSION['userid'] )) {
@@ -161,6 +160,8 @@ $app->hook( 'slim.before.dispatch', function() use($person) {
                        $response['error'] = true;
                        $response['message'] = _("Access Denied");
                        $response['errorcode'] = 401;
+                       echoResponse($response );^M
+                       $app->stop();^M
                }
        }
```

**Comment by timlegge** [comment]
Fixed by https://github.com/samilliken/openDCIM/pull/1187

**Comment by timlegge** [comment]
Fix was merged.  @FliesLikeABrick Please test and close
