### ISSUE TITLE
one to many arbitrary cable/port mapping

### ISSUE THREAD

**Issue by bettaa** [samilliken/openDCIM#1159]
We use MTP to LC (1 connector to 4 connectors)breakouts from a 40gig QSFP port. I would like to be able to arbitrarily break out a cable/port into sub-cables/ports for connecting to patch panels.

**Comment by samilliken** [comment]
There you go.   I assigned it to you to figure out the best way to write that feature in.

**Comment by skipper00** [comment]
mmm same issue...that's a good question....
