### ISSUE TITLE
Please add container (containers) prefix before DC name in dropdown list

### ISSUE THREAD

**Issue by amadis** [samilliken/openDCIM#1162]
Hi! I try version 19.1 in demo site.

For example I have two containers - Town1 and Town2, in both I have one datacanter, the name in both is DC1. So when I try to define a zone I have two DC1 lines in dropdown menu in "Data Center Zones" dialog.

https://i.imgur.com/IDOEM6N.png

Please add container (containers if multiple?) prefix before DC name in aproproate dropdown lists...

Thank you!

**Comment by samilliken** [comment]
Um, no.    Name your data centers with enough unique info if you want that to always show.
