### ISSUE TITLE
switch port status not correct v19

### ISSUE THREAD

**Issue by holdmont** [samilliken/openDCIM#1163]
Hi
i updated to version 19. Now port status of switch not working. Refresh note and other work corrrectly, but port status not.
With snmpwalk it works correctly:

 snmpwalk -v 2c -c public 10.10.7.44 IF-MIB::ifOperStatus
IF-MIB::ifOperStatus.1 = INTEGER: down(2)
IF-MIB::ifOperStatus.2 = INTEGER: up(1)
IF-MIB::ifOperStatus.3 = INTEGER: down(2)
IF-MIB::ifOperStatus.4 = INTEGER: down(2)
IF-MIB::ifOperStatus.5 = INTEGER: up(1)
IF-MIB::ifOperStatus.6 = INTEGER: up(1)
IF-MIB::ifOperStatus.7 = INTEGER: up(1)
IF-MIB::ifOperStatus.8 = INTEGER: up(1)
IF-MIB::ifOperStatus.9 = INTEGER: up(1)
IF-MIB::ifOperStatus.10 = INTEGER: up(1)

Can you help me please?
thanks
Filippo

**Comment by skipper00** [comment]
+1

**Comment by timlegge** [comment]
Check your Configuration under Reporting.  It is likely set to OptIn which requires the device to have a Tag of Poll associated to the device...

If you change to OptOut you may want NoPoll on some devices as the SNMP check is slow if it does not work.

Tim

**Comment by holdmont** [comment]
thanks...
resolved putting OptOut.
