### ISSUE TITLE
Delete cabinets by Bulk Delete

### ISSUE THREAD

**Issue by AleSbTNS** [samilliken/openDCIM#1172]
Hello dear Community. I'm trying to delete cabinets by Bulk importer. I mean, imagine I created a lot of cabinets without kW info. I need to create it again, with the right information? Or I'm able to edit/delete them? Of course, I want to avoid one-by-one edit.

Thanks for all!

**Comment by samilliken** [comment]
Already answered on mailing list.   No, this does not exist.
