### ISSUE TITLE
Duplicate call to getPortName and getPortAlias

### ISSUE THREAD

**Issue by timlegge** [samilliken/openDCIM#1173]
Hi

When a user clicks the "Refresh Port Names" or "Refresh Port Notes" the code make two calls to getPortNames and getPortAlias (depending on which is called) in very short order which makes somewhat slow snmp calls for the same information.

It would be better to assign the results of getPortXXXXX to a variable and use it instead thereby making the SNMP call once

https://github.com/samilliken/openDCIM/blob/ec3c12acff2e936f1a8ecce71d9500dbb15654d9/devices.php#L472
https://github.com/samilliken/openDCIM/blob/ec3c12acff2e936f1a8ecce71d9500dbb15654d9/devices.php#L480

and

https://github.com/samilliken/openDCIM/blob/ec3c12acff2e936f1a8ecce71d9500dbb15654d9/devices.php#L486
https://github.com/samilliken/openDCIM/blob/ec3c12acff2e936f1a8ecce71d9500dbb15654d9/devices.php#L495
A possible patch is here.  There may be a reason to do it that way but snmp calls being somewhat expensive making the call twice seems excessive.

[duplicate.patch.txt](https://github.com/samilliken/openDCIM/files/3592894/duplicate.patch.txt)

I can send a PR specific to this if you would like

Tim

**Comment by timlegge** [comment]
@samilliken and @wilpig I am not sure if you have seen this issue yet.  I used the patch from above in my environment to avoid the duplicate call and it seems to work.

Tim

**Comment by samilliken** [comment]
@timlegge  can you please submit the patch as a pull request?

**Comment by timlegge** [comment]
will do

**Comment by timlegge** [comment]
fixed in https://github.com/samilliken/openDCIM/pull/1194

**Comment by timlegge** [comment]
Please close
