### ISSUE TITLE
devices.php requests Pictures directory index when device image is blank

### ISSUE THREAD

**Issue by timlegge** [samilliken/openDCIM#1174]
If a device does not have a front or back image assigned the devices.php makes a request for:

https://github.com/samilliken/openDCIM/blob/ec3c12acff2e936f1a8ecce71d9500dbb15654d9/devices.php#L1956

GET /pictures//

This results in a response that is (in my case) 52k for information it will never use.  The simplest fix would be to make a request for a non existent file.  

There is likely a better approach.

**Comment by timlegge** [comment]
you might want to look at this one too @samilliken I used the simplest approach of asking for a file that will result in a 404.  This seems to make the logic work to hide the image if a template image was not provided but did seem hacky to me...

**Comment by wilpig** [comment]
I've seen them both, just don't care. The no image is a detection method to keep the screen from doing strange things. Haven't looked at it in years but it was done on purpose.

On Sep 21, 2019 8:16 PM, Timothy Legge <notifications@github.com> wrote:

you might want to look at this one too @samilliken<https://github.com/samilliken> I used the simplest approach of asking for a file that will result in a 404. This seems to make the logic work to hide the image if a template image was not provided but did seem hacky to me...

**Comment by timlegge** [comment]
my production server gives a forbidden or 404 error (forget which) for indexing a dir so not a big issue for me.  I was looking into the performance of the devices.php file on my development laptop where I noticed the index page being requested.

You can close if you like...
