### ISSUE TITLE
Allow CDU power connections to cross cabinets

### ISSUE THREAD

**Issue by AleSbTNS** [samilliken/openDCIM#1189]
I know from reading, that as it is consider as a "bad practice", there are no way to create power conection between cabinets. Eventhough, that's the way we have the things connected.
Could someone tell me where, (in the code), it checks that the PDU and the device where in the same cabinet? I can't find it!
I'm planning to modify the code myself, of course.

Thanks!

**Comment by samilliken** [comment]
If you search the mailing list archives, the answer is in there, somewhere, but I'm shutting this down as having it open would imply that we would change the code, which we won't.
