### ISSUE TITLE
Issues introduced with https://github.com/samilliken/openDCIM/pull/1083

### ISSUE THREAD

**Issue by timlegge** [samilliken/openDCIM#1193]
Missing database value in fac_Config and

[Thu Oct 31 01:01:41.779540 2019] [php7:error] [pid 927] [client 192.168.122.1:49014] PHP Fatal error:  Uncaught Error: Call to undefined method stdClass::GetDeptByID() in /var/www/openDCIM/classes/Cabinet.class.php:115\nStack trace:\n#0 /var/www/openDCIM/classes/Cabinet.class.php(242): Cabinet::RowToObject(Array)\n#1 /var/www/openDCIM/cabnavigator.php(99): Cabinet->GetCabinet()\n#2 {main}\n  thrown in /var/www/openDCIM/classes/Cabinet.class.php on line 115
[Thu Oct 31 01:02:02.875215 2019] [php7:warn] [pid 928] [client 192.168.122.1:49026] PHP Warning:  Creating default object from empty value in /var/www/openDCIM/classes/Cabinet.class.php on line 114, referer: 

Seems to be fixed via:

 diff --git a/classes/Cabinet.class.php b/classes/Cabinet.class.php
index 1d8bd27b..5b21f273 100644
--- a/classes/Cabinet.class.php
+++ b/classes/Cabinet.class.php
@@ -111,9 +111,10 @@ class Cabinet {
                
            global $config;
            if($config->ParameterArray["AssignCabinetLabels"]=="OwnerName"){
-           $dep->DeptID=$dbRow["AssignedTo"];
-           $dep->GetDeptByID();
-           $cab->ShowCabinetLabel=$dep->Name;}
+           $cab->DeptID=$dbRow["AssignedTo"];
+           $dept = new Department();
+           $dept->GetDeptByID();
+           $cab->ShowCabinetLabel=$dept->Name;}
 
            if($config->ParameterArray["AssignCabinetLabels"]=="KeyLockInformation"){
               $cab->ShowCabinetLabel=$dbRow["Keylock"]; }

**Comment by samilliken** [comment]
Please submit as a pull request.

**Comment by samilliken** [comment]
Or better yet, just commit the fix.

**Comment by timlegge** [comment]
fixed in https://github.com/samilliken/openDCIM/pull/1194
