### ISSUE TITLE
LDAP ISSUE OPENDCIM

### ISSUE THREAD

**Issue by chandukalyani** [samilliken/openDCIM#1212]
I have installed Opendcim 19 version tool but facing issue with LDAP.
Once we enable LDAP authentication , Browser contionously asking for the credentials .
Kindly help me.

**Comment by samilliken** [comment]
This is not a bug in openDCIM, it is a configuration issue.    GitHub issues are for bug reports.    Please follow the instructions and use the MAILING LIST for questions about how to configure.
