### ISSUE TITLE
user administration and RBAC access....

### ISSUE THREAD

**Issue by chandukalyani** [samilliken/openDCIM#1213]
We're looking at implementing openDCIM in a fairly large environment, where those responsible for application support and user management may not necessarily be the same folks responsible for managing and maintaining the facilities and other "content" within openDCIM.

But i see every user logged in getting all the permission cannot we restrict it. At least they should not have access to delete .

Their is no contact administration tab in 19.01 version , also suggest me how can we delete the users.

Kindly help

**Comment by wilpig** [comment]
1. Use the mailing list for support.
2. The user administration has not changed.
3. If your users are getting full rights upon logging in you must have ldap set up to give them full rights or made a change to the underlying code.
4. **Use the mailing list for support.**
