### ISSUE TITLE
bulk import operations for Custom Device Attributes on all of my devices

### ISSUE THREAD

**Issue by mrIom** [samilliken/openDCIM#1215]
I want to be able to add specific columns of Custom Attributes that I have defined on every Device to the excel "Bulk Device Import Template".

As I see it, I have to modify the bulk_importer.php. It seems to be very similar to the funcionality of importing "CustomTags". The custom tags has their own database table and relation with the device. Only difference that I see is that for the tags is checking for every tag if needs to be created or already exists and calling Device->setTags(). In the case of a specific Custom Attribute is a whole new column on the excel, so it needs to check first if that Column Attribute exists in the database table 'DeviceCustomAttribute', then been able to add the value by using InsertCustomValue() on Device.class. I'm on the right track?

I know that this is something very specific to me, and it is not general as everyone could have any number of custom attributes (new columns on the excel) they want to add. I just want some pointers in where to look to modify, and if it is too complex and will not fit to my needs. I'm on the right track? Something already exists that I can take a look at?

Thanks in advance.

**Comment by Riton18** [comment]
Hello,
I modified bulk_importer.php to integrate the custom attributes defined in the configuration.
If it can help you.
attached php file.
Regards.

[bulk_importer.zip](https://github.com/samilliken/openDCIM/files/4192888/bulk_importer.zip)

**Comment by mrIom** [comment]
Thanks a lot @Riton18 , will definitely check it out!

**Comment by Riton18** [comment]
Hello,
I also modified the code to integrate the "MfgDate" and WarrantyExpire "fields. Attached is the correct file.
Thank you for your interest

Henri.
[bulk_importer.zip](https://github.com/samilliken/openDCIM/files/4203211/bulk_importer.zip)

**Comment by mrIom** [comment]
Great! Thanks a lot, it works like a charm!
I have a question that is unrelated to the bulk importer, but wanted to ask you if you have encounter the problem, since it is related to Custom attributes:
When you go to Data Center Device Templates, to edit a Model, and you modified one of the Custom fields (I have one that is named Family since it is common for every Device using this Model. When I hit the 'Update Devices', it should copy this field to all of the devices, right? It doesn't for me. Do you have a solution to have only this field in the template Model, and be able to have it exported in every Device that uses the Device Template?

BTW Thanks for the bulk importer, have save me a ton!

**Comment by samilliken** [comment]
The "Update Devices" button simply updates the default values for weight
and wattage.   We've struggled with a better name to call that button.

The reason is that the template is simply your starting point for your
device, not the end of defining it.

Scott

**Comment by mrIom** [comment]
Ok, thanks @samilliken !
