### ISSUE TITLE
Feature Request: Allow CDUs to be connected to other CDUs

### ISSUE THREAD

**Issue by Chewie9999** [samilliken/openDCIM#1216]
I know this is bad design, but sadly this is all too common and documenting the situation is still necessary:

It is possible to allow the selection of a CDU as a connection from another CDU?
Currently, if you select it, of course you have to select a port, which is wrong, as it's a plug you would have to select, not a port/socket.
I know you could just add 1 more port and name it "plug" or something, but that would get confusing.

I suggest being able to select a CDU, and either have a specific port listed as "CDU plug" automatically (or similar) in the list, or just be able to select the CDU without have to select a port.
At the moment (in 19.01), if you don't select a port and click save, then nothing is recorded.
This request is similar to #660, but this was closed a long time ago and not sure why.

**Comment by samilliken** [comment]
Um, no.
