### ISSUE TITLE
Cannot add more devices type

### ISSUE THREAD

**Issue by panhala** [samilliken/openDCIM#1217]
Hi team,

Could you tell me how to add more devices type?

**Comment by mrIom** [comment]
This issue being responded here: https://github.com/samilliken/openDCIM/issues/767
Also on the FAQ (https://opendcim.org/faq.html) says:

**why can't i add more devicetype values?**
The DeviceTypes values will change the behavior of the user interface, therefore the list needs to remain static or it will break functionality. We recommend that you use tags to designate more specific categories of devices.

**Comment by nizzoball** [comment]
They realky did a oretty good job of covering all of the bases with the current DeviceTypes. I cant think of much that wouldnt fall under one of the existing types. When in doubt, use Appliance
