### ISSUE TITLE
Bulk Device Moves - needs a DeviceID and DataCenterID

### ISSUE THREAD

**Issue by mrIom** [samilliken/openDCIM#1218]
The Bulk Device Moves/Deletes, Bulk Move process needs a DeviceID, DataCenterID, and KeyField?
The other fields needed are no problem, but I thought that I could get the DeviceID/DataCenterID by exporting a report. But no report exports those IDs, since they are part of the internal logic of the database I can relate. 

But since it is needed for bulk operations, why not include them in some kind of export? I will have to go to every device to get the DeviceID, and that will defeat the purpose of having a Bulk Move operation (not going to each Device).

**Comment by nizzoball** [comment]
Its pretty easy to modify or create reports that include DeviceID.  Just need to know a little php. Other option is to create a sql query against the database directly and export to csv with something like dbeaver. I prefer modifying or creating my own reports though. It really is pretty easy yo grab one to use as a template and add your own data leveraging the classes.

**Comment by mrIom** [comment]
Thank you, will try to do that.

**Comment by samilliken** [comment]
So in response to the initial statement - if you look at the wiki, it explains that you aren't actually looking for the DatabaseKey field for the Device and Cabinet.

However, there is already a report that exports that information, it's the "Export Data Center for CFD (XML)" Report.

That being said, I'm actually modifying the Move/Delete operation to actually allow you to specify the Database Key fields.
