### ISSUE TITLE
Error in search.php: Line 167

### ISSUE THREAD

**Issue by pawsey-kbuckley** [samilliken/openDCIM#1221]
Not sure why I (or anyone else?) haven't traversed this code path before but I have 
just been hit by

PHP Parse error: symtax error, unexpected '[' in /var/www/html/openDCIM/search.php 

which suggests an erroneous left-square-bracket, visible at line 167 in search.php:

```
166			$temp[$x]['rights']=$device->Rights;
167			$cabtemp[$device->Cabinet] = [];
168			++$x;
```

**Comment by pawsey-kbuckley** [comment]
And just to say that "no", I can't see an error there either, but that's what the log is telling me!

**Comment by wilpig** [comment]
There isn't an error there, it's your version of php. It doesn't like the short hand designator for an empty array. It's an issue that we need to address with the removal of support for PHP 5.3 and rhel6

On May 11, 2020 11:08 PM, pawsey-kbuckley <notifications@github.com> wrote:

And just to say that "no", I can't see an error there either, but that's what the log is telling me!

**Comment by pawsey-kbuckley** [comment]
> There isn't an error there, it's your version of php. 

Makes sense. I'd cloned my "production" version back into a CentOS610 LAMP VM
and just couldn't work out why I hadn't seen the issue with the production deployment.

Cheers,
Kevin
