### ISSUE TITLE
Inventory PDF Report free space

### ISSUE THREAD

**Issue by ekrichbaum** [samilliken/openDCIM#1231]
Is there a function to be able to get the free space of all cabinets?  i.e. I'd like to do a $tenantList=$dev->GetTop10Tenants(); down to 9 and put the amount of free space on that pie.

**Comment by samilliken** [comment]
Please send questions to the mailing list, rather than opening an issue.

The answer to your question is no, but that's the beauty of open source - you can roll your own with your modifications.
