### ISSUE TITLE
DC's LDAP Permission

### ISSUE THREAD

**Issue by AleSbTNS** [samilliken/openDCIM#1238]
Good morning, everyone. I am using LDAP for user management; and since we have many DC's and many people coming into DCIM I wonder, is there any way to prohibit some users from seeing other DC's?
Not to hide information, but to prevent them from modifying the information of other DCs among themselves.

I mean, user A can see and modify DC1 and user B can see and modify DC2, but A can't even see DC2, and vice versa.

Thank you!

**Comment by samilliken** [comment]
No, we have not added in the ability to basically federate the SiteAmin
privs.    We've looked into it, but it would require modifying nearly every
class and file, which we simply don't have the resources to work on.

Scott

**Comment by AleSbTNS** [comment]
Ok Scott, I perfectly understand. I though the same about modifying all the classes and files. I will try to solve it in some way, in case I do, I'll make a pull request with the feature.

Thanks.
