### ISSUE TITLE
20.01 Ldap attribute mapping bug

### ISSUE THREAD

**Issue by havoc78** [samilliken/openDCIM#1240]
Found a weird issue. 
When under the configuration attribute mapping section, if you use the default "givenName" value for FirstName, the users FirstName field is not populated with ldap auth. It shows a blank under the user details sections. When this is changed to "givenname" (Note the lowercase N), then the details are populated correctly. User's firstname field is populated.

**Comment by samilliken** [comment]
It is case sensitive and dependent upon your schema.
