### ISSUE TITLE
DIRECTORY_RIGHTS 

### ISSUE THREAD

**Issue by kseltar** [samilliken/openDCIM#1242]
the documentation need to be fixed about the application root DIRECTORY_RIGHTS 

rightscheck.php need explain the right permission since the directory like 

chmod 755 -R ./ 

and chown if is really necessary

the other point is that the application never explains that need create <approot>/pictures <approot>/drawings and the rights
because that need have upload permisions for datacenter maps/plain  and hardware, or permit the app create automated

obs: out of the point need add a object for accounting inventory registration number separate from the factory serial number or part number

**Comment by syndgr** [comment]
> obs: out of the point need add a object for accounting inventory registration number separate from the factory serial number or part number

Not sure if you're asking for this to be a feature but devices already have an "Asset Tag" property. You can also add custom attributes (Edit Configuration > Custom Device Attributes).

**Comment by syndgr** [comment]
Could the documentation benefit from a bit of a tidy up or review?

Perhaps one or a combination of:
- Remove INSTALL, in favour of README.md to remove any duplication of instructions?
- Use the openDCIM wiki as the definitive resource and as such in the INSTALL, README.md and UPGRADE files ask the user to refer to the wiki?

The only issue I see with the last point is that if something significantly changed you'd need to caveat the wiki instructions with things like "only applicable to version X", whereas the instructions within each tarball are pertinent to that version only and the wiki has specific pages (e.g. "installing openDCIM 20.01 on Ubuntu 18.04 LTS").

**Comment by samilliken** [comment]
Yes, it could definitely stand an update.   Feel free to make some changes
to reflect what you've described.    Referring everybody to the wiki is the
most logical choice as it will then only require one update to
documentation for the future.

Scott
