### ISSUE TITLE
Cabinets Labels don't display

### ISSUE THREAD

**Issue by DOCPROF** [samilliken/openDCIM#1251]
After updating from version 18.02 to version 20.01, the location of the cabinets is no longer displayed on the map of the datacenter.
I checked in the configuration and I cannot leave the "Location" field.
![liste](https://user-images.githubusercontent.com/8957491/95629339-06234b00-0a80-11eb-9f46-c726bb379186.png)

Why is this field not possible?
![location](https://user-images.githubusercontent.com/8957491/95629376-14716700-0a80-11eb-8084-bd5139c55134.png)

Thx.

**Comment by samilliken** [comment]
Already reported and fixed for next release.

https://github.com/samilliken/openDCIM/commit/0c1c5c7af6995c552ffa7ae1180b08f27aaa91a5
