### ISSUE TITLE
Child devices not cleared properly when sent to Storage Room

### ISSUE THREAD

**Issue by samilliken** [samilliken/openDCIM#1269]
If you move a child device to a storage room it retains the parent device information, so when you click on it, it ends up showing within that parent device.   Ok, not desire behavior, but nothing bad so far.

Now delete that parent device.   Then try to view the device in the Storage Room.   Or dispose of it.   Or anything outside of a direct API manipulation of it - you'll get hung.

Need to make sure that the ParentDevice field gets cleared whenever a child device is sent to a Storage Room.

**Comment by wilpig** [comment]
I thought we had it to where you couldn't just move a child into storage and it had to move into another parent which should update that link then.

**Comment by samilliken** [comment]
Possibly.    These could be from ones that were moved before that code was added, so they're stuck now unless I do backend jiggery pokery.   When I dig into the code we'll see - I may just add a check in the storageroom.php file and clear that bit if it refers to an invalid parent device.

**Comment by samilliken** [comment]
Reproducible.    Create a chassis with a child device in a cabinet.   Now move the chassis to the storage room.   Child device is not getting moved with it.   This could be a regression, as comments indicate that this did work correctly in the past.

**Comment by samilliken** [comment]
Or not.   Trying to figure out exactly how I got into this condition.

**Comment by samilliken** [comment]
I can't get this to reproduce and think it was caused from some moves that happened before the logic was added.  Closing unless I can reproduce it again in the future.
