### ISSUE TITLE
bulk_network.php using $_SESSION without session_start();

### ISSUE THREAD

**Issue by dlabrie** [samilliken/openDCIM#1272]
Problem:

Uploading a file leads to errors saying the file cannot be found.
This is due to the filename being stored in the $_SESSION variable without having a PHP SESSION Cookie.

Solution:

Adding session_start(); at the beginning of the file resolves the issue

**Comment by samilliken** [comment]
If you are using the current db.inc.php-dist template, there is already a session_start() call as long as you are not using the CLI, so therefore this is invalid, as db.inc.php is globally called at the top of each page.
