### ISSUE TITLE
login_ldap.php: invalid ldap login (even without specifying username and password) allows full access in dcim

### ISSUE THREAD

**Issue by k8blsalat** [samilliken/openDCIM#1276]
first of all: we authenticate on our Active Directory and I can't say since when exactly the problem exists but we haven't changed anything that caused the problem.
the problem also occurs in version 20.01
for this example i logged in with (non existing) AD user "nonpermitteduserwithoutpassword" and here the apache log output.
After that i am successfully logged in to the dcim interface and have all rights.

[Wed May 26 12:26:45.762865 2021] [:error] [pid 12281] [client x.x.x.x:54011] User search filter: (|(sAMAccountName=nonpermitteduserwithoutpassword)), referer: https://opendcim.domain.de/login_ldap.php?logout
[Wed May 26 12:26:45.764043 2021] [:error] [pid 12281] [client x.x.x.x:54011] PHP Warning:  ldap_search(): Search: Operations error in /var/www/html/openDCIM-20.02/login_ldap.php on line 142, referer: https://opendcim.domain.de/login_ldap.php?logout
[Wed May 26 12:26:45.764157 2021] [:error] [pid 12281] [client x.x.x.x:54011] PHP Warning:  ldap_get_entries() expects parameter 2 to be resource, boolean given in /var/www/html/openDCIM-20.02/login_ldap.php on line 143, referer: https://opendcim.domain.de/login_ldap.php?logout
[Wed May 26 12:26:45.871135 2021] [:error] [pid 12281] [client x.x.x.x:54011] nonpermitteduserwithoutpassword has ReadAccess by membership in , referer: https://opendcim.domain.de/login_ldap.php?logout
[Wed May 26 12:26:45.871913 2021] [:error] [pid 12281] [client x.x.x.x:54011] nonpermitteduserwithoutpassword has WriteAccess by membership in , referer: https://opendcim.domain.de/login_ldap.php?logout
[Wed May 26 12:26:45.872560 2021] [:error] [pid 12281] [client x.x.x.x:54011] nonpermitteduserwithoutpassword has DeleteAccess by membership in , referer: https://opendcim.domain.de/login_ldap.php?logout
[Wed May 26 12:26:45.873329 2021] [:error] [pid 12281] [client x.x.x.x:54011] nonpermitteduserwithoutpassword has AdminOwnDevices by membership in , referer: https://opendcim.domain.de/login_ldap.php?logout
[Wed May 26 12:26:45.874034 2021] [:error] [pid 12281] [client x.x.x.x:54011] nonpermitteduserwithoutpassword has RackRequest by membership in , referer: https://opendcim.domain.de/login_ldap.php?logout
[Wed May 26 12:26:45.874799 2021] [:error] [pid 12281] [client x.x.x.x:54011] nonpermitteduserwithoutpassword has RackAdmin by membership in , referer: https://opendcim.domain.de/login_ldap.php?logout
[Wed May 26 12:26:45.875559 2021] [:error] [pid 12281] [client x.x.x.x:54011] nonpermitteduserwithoutpassword has ContactAdmin by membership in , referer: https://opendcim.domain.de/login_ldap.php?logout
[Wed May 26 12:26:45.876185 2021] [:error] [pid 12281] [client x.x.x.x:54011] nonpermitteduserwithoutpassword has BulkOperations by membership in , referer: https://opendcim.domain.de/login_ldap.php?logout
[Wed May 26 12:26:45.876839 2021] [:error] [pid 12281] [client x.x.x.x:54011] nonpermitteduserwithoutpassword has SiteAdmin by membership in , referer: https://opendcim.domain.de/login_ldap.php?logout

**Comment by samilliken** [comment]
Unable to validate this use case with an openLDAP backend.    Will need Wilbur to give it a try with Active Directory.

**Comment by wilpig** [comment]
Not seeing this behavior on the dev instance that is AD backed.  What version of PHP is in use?

`[Wed May 26 12:26:45.764043 2021] [:error] [pid 12281] [client x.x.x.x:54011] PHP Warning: ldap_search(): Search: Operations error in /var/www/html/openDCIM-20.02/login_ldap.php on line 142`

**Comment by k8blsalat** [comment]
thanks for your quick response:

PHP 7.0.33-0ubuntu0.16.04.15 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.33-0ubuntu0.16.04.15, Copyright (c) 1999-2017, by Zend Technologies

**Comment by k8blsalat** [comment]
no we don't use any group mappings at all.

**Comment by samilliken** [comment]
Then you need to use the apache mod_ldap module instead and set your authentication in db.inc.php to APACHE.   If you're using the built-in LDAP for openDCIM then you MUST map groups for authorization.

**Comment by wilpig** [comment]
At a minimum I suggest using the site access group and at least mapping it to your everyone group for AD.  I'm testing without groups now to see if I can find a condition where the ldap module allows an invalid user to get access.

**Comment by k8blsalat** [comment]
hmn ok that is not quite correct. The authentication against our ADS already worked fine without the group mapping. Our security concept for opendcim does not require it. However a colleague found a workaround which he will post here later.

**Comment by wilpig** [comment]
The bug has been fixed, see the related commit.  You should still at a minimum set a site access group.

**Comment by schirrmie** [comment]
Hey,
the commit solved the issue, thanks!
But you should also check the return of ldap_get_entries

`$ldapResults=ldap_get_entries($ldapConn,$ldapSearch);`

You should check of false if an error occur and also check the size of the returned array.
ldap_get_entries returns true even if no results are found.
`if($ldapResults["count"]==0) return false;`
