### ISSUE TITLE
Audit automation feature

### ISSUE THREAD

**Issue by rvtis** [samilliken/openDCIM#1280]
It would be FANTASTIC if certifying an audit of a rack meant all devices inside were certified as well. So far it's so annoying to certify each and every device

**Comment by samilliken** [comment]
It doesn't really work that way, but I will make an enhancement to show it clearly.    When you pull via the API it is much clearer - a device is considered audited any time that a cabinet is audited, but I realized that the device view still doesn't reflect that.   I'll add that in.

**Comment by wilpig** [comment]
That isn't right. You can audit a cabinet to verify that the devices named are present but the devices themselves might not match your inventory so we definitely don't want to cascade that

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by samilliken** [comment]
That does not match the original intent of the buttons and features.
There's no such thing as a half assed audit in terms of policy, only in
real life implementation.

Scott
