### ISSUE TITLE
Create RESTful APIs as needed

### ISSUE THREAD

**Issue by samilliken** [samilliken/openDCIM#349]
Just sticking this out here to tie commits to as we implement some.  There's a lot of thought that is going to have to go into this.

http://www.openlogic.com/wazi/bid/215833/Apache-and-RESTful-Web-Services

Output would initially be JSON, but may decide to do some in XML on an as needed basis.

The documentation on this will probably be the biggest pain, as we can always ship a url_rewrite recipe for apache, but there are so many people running on non-supported architectures.

**Comment by samilliken** [comment]
We have our basic set of API calls.  More will be added in the future, but under other issues.

**Comment by TafThorne** [comment]
Sounds great! Thanks for getting this feature added.
