### ISSUE TITLE
Expand Virtualization options to include proxmox

### ISSUE THREAD

**Issue by wilpig** [samilliken/openDCIM#367]
Proxmox Wiki:
http://pve.proxmox.com/wiki/Proxmox_VE_API
Proxmox API:
http://pve.proxmox.com/pve2-api-doc/

**Comment by samilliken** [comment]
When Hypervisor == ProxMox, need the UI to mangle the SNMP area such that:

SNMPCommunity = "Node Name"
SNMPv3Passphrase = "Username"
SNMPv3 PrivPassphrase = "Password"

All the rest get hidden.
