### ISSUE TITLE
Power Source should allow multiple load oids as the CDU device does

### ISSUE THREAD

**Issue by m0zes** [samilliken/openDCIM#473]
We've got a MGE Galaxy UPS that doesn't provide a single OID for load, just load per phase. Is there any chance we can have multiple and have openDCIM calculate the total load as it does for CDU devices?

**Comment by samilliken** [comment]
This table is going away and everything will simply be in the fac_PowerPanel table.  A PowerSource would simply be a PowerPanel with no ParentPanelID defined.  In other words, this is getting completely reworked.
