### ISSUE TITLE
Possibly introducing check on size of the output of 'report_network_map.php'

### ISSUE THREAD

**Issue by AndHam89** [samilliken/openDCIM#486]
In case the size of the to be generated file for dot is too large an exception occurs and the screen stays blank. The apache log shows the below error message. 

It would be good to avoid the situation of an empty screen. If it is possible either check on the size of the graph to be generated by dot or to check for the return code of the external call and in case of an exceptional situation issue a message to the user that the problem size is too large.

```log
[Wed Jul 09 18:36:17.004288 2014] [core:notice] [pid 1447] AH00094: Command line: '/usr/sbin/httpd2-prefork -f /etc/apache2/httpd.conf -D SSL -D SYSTEMD -D FOREGROUND'
Error: /tmp/graph_n6ql45: syntax error in line 99 near '['
dot: graph is too large for cairo-renderer bitmaps. Scaling by 0.349768 to fit
Warning: teal is not a known color.
dot: graph is too large for cairo-renderer bitmaps. Scaling by 0.349768 to fit
dot: graph is too large for cairo-renderer bitmaps. Scaling by 0.349768 to fit
```

**Comment by samilliken** [comment]
This appears to be a resolved issue, in that the script now lets you know when there has been an error in processing.  I don't know what more we can do along this issue.  You can open a new issue if you feel there is still something else to do.
