### ISSUE TITLE
Default values from fac_Config should be configurable (mostly)

### ISSUE THREAD

**Issue by AndHam89** [samilliken/openDCIM#489]
Default values such as the 'english' value for "mUnits" in table "fac_Config" should be configurable through the "Edit Configuration" menu. 

In this special case the question is if there ever will be sensor templates with "english" metric values but the "Measurement Units" otherwise in "metric" or vice verse.

**Comment by samilliken** [comment]
This issue has become moot as the database now handles conversion properly - all values are stored in the format specified under Site Configuration, whether an individual sensor template matches that preference or not.
