### ISSUE TITLE
Create SNMP class

### ISSUE THREAD

**Issue by wilpig** [samilliken/openDCIM#506]
In order to simplify our life and pull all the various bits into one place we need a central SNMP class.  All calls for any snmp lookup will go through it and all version specific silliness can be worked out there.

ie

class openSNMP
function read() // read a single value
function walk() // walk a tree and return an array

Inside of these points we can look for advanced functions available in PHP5.4, 5.5+ and if they exist use them, if not we can fall back to older methods finally terminating with using the command line.  This should save us future headaches.

**Comment by samilliken** [comment]
While there will still be some conversions to do as we go back and touch code, the class is there and is being used for most functions.
