### ISSUE TITLE
isValidURL doesn't return correctly for the Phone Directory lookup

### ISSUE THREAD

**Issue by samilliken** [samilliken/openDCIM#509]
The regex is returning that corporate directory lookups such as http:/blah.url/userid= are not valid, and therefore the button to lookup a contact isn't being displayed.

**Comment by wilpig** [comment]
Results from new filter.

http:/blah.url\userid= invalid
http://blah.url/userid= invalid
http://blah.url/users valid
https://blah.google/users/ valid
https://blah.google/users/? valid
https://blah.google.com/users.php?userid=this valid

**Comment by wilpig** [comment]
After banging my head against this I need to talk to whomever made the request.  The url you mentioned isn't RFC compliant from the best I can tell and it fails against everything I throw at it.  I'm ready to just close this as not a bug.
