### ISSUE TITLE
Create methods to help determine cabinet of child devices

### ISSUE THREAD

**Issue by samilliken** [samilliken/openDCIM#511]
Need to have two methods (or more if you determine needed after getting started)

Device::GetParentCabinet( $DeviceID ) -> returns object Cabinet which is parent of $DeviceID

Device::GetCabinetChildDevices( $CabinetID ) -> returns array of Device objects that are children of chassis in the specified $CabinetID

**Comment by wilpig** [comment]
This method is no longer needed since all children now use the same CabinetID as their parent.  Closing.
