### ISSUE TITLE
Paths.php allows to remove the patch even when the user has no privileges

### ISSUE THREAD

**Issue by sbraitti** [samilliken/openDCIM#512]
diff --git a/paths.php b/paths.php
index 164620e..227639f 100644
--- a/paths.php
+++ b/paths.php
@@ -33,19 +33,23 @@
        }

        if(isset($_POST['bot_eliminar'])){
-               $port=new DevicePorts();
-               for ($i=1;$i<$_POST['elem_path'];$i++){
-                       if ($_POST["PortNumber"][$i]>0){
-                               $port->DeviceID=$_POST["DeviceID"][$i];
-                               $port->PortNumber=$_POST["PortNumber"][$i];
-                               $port->getPort();
-                               //only remove connections between front ports
-                               if ($port->ConnectedPort>0){
-                                       $port->removeConnection();
+               if ($user->WriteAccess) {
+                       $port=new DevicePorts();
+                       for ($i=1;$i<$_POST['elem_path'];$i++){
+                               if ($_POST["PortNumber"][$i]>0){
+                                       $port->DeviceID=$_POST["DeviceID"][$i];
+                                       $port->PortNumber=$_POST["PortNumber"][$i];
+                                       $port->getPort();
+                                       //only remove connections between front ports
+                                       if ($port->ConnectedPort>0){
+                                               $port->removeConnection();
+                                       }
                                }
                        }
+                       $status.=__("Front connections Deleted");
+               } else {
+                       $status.=__("You have no privileges!");
                }
-               $status.=__("Front connections Deleted");
        }

        if(isset($_POST['action']) || isset($_REQUEST['pathid']) || (isset($_REQUEST['deviceid']) && isset($_REQUEST['portnumber']))){
@@ -454,8 +458,7 @@
                        //End of path table
                        $path.="\t<tr>\n\t\t<td colspan=6>&nbsp;</td>\n\t</tr></table></div>";

-                       // need to add an additional check for permission here if they can write
-                       if(!isset($_GET['pathonly'])){
+                       if(!isset($_GET['pathonly']) and $user->WriteAccess){
                                //Delete Form
                                $path.= "<form action=\"{$_SERVER["PHP_SELF"]}\" method=\"POST\">\n";
                                $path.= "<br>\n";

**Comment by jomigom** [comment]
I have difficulties with the subject of rights of users:
-The "Path Connections" menu is only displayed when the user has right "SiteAdmin". However it became necessary to control the rights of users deleting connections. Does the site administrator should not be able to do this?.
-Is the "Write" right for all devices?
-When should a user see the paths of connections?
-When should a user be able to delete paths of connections?
-When should a user be able to create the paths of connections?
-What devices could be used to create paths of connections? Currently the algorithm uses all devices, regardless of the rights of users or owners of the devices

**Comment by samilliken** [comment]
A user with "ReadAccess" should have the ability to view any device and/or
connection, regardless of their department membership.

A user with "AdminOwnDevices" should have the ability to read/write any
device that is owned by a department that the user is a member of.
Thinking this through - they should be able to delete a connection for
which at least one endpoint is owned by a department that the user is a
member of.  They should be able to establish a connection between any
department-owned device and any other department-owned device.

In other words, if you are a member of the Accounting Department and you
want to uplink to a distribution switch owned by Networking, that
connection would have to be made by someone with Global Write access.  If
you want to disconnect the existing connection, you should be able to do
that.

SiteAdmin isn't a root type of account - giving that privilege doesn't
affect your read/write ability on devices.  It simply gives you the rights
to change the infrastructure - cabinets, rows, zones, etc.

ContactAdmin allows you to manage users (and the soon to be removed
Contacts).

That make sense?


On Fri, Jan 16, 2015 at 6:19 AM, Jose Miguel Gomez <notifications@github.com

**Comment by wilpig** [comment]
Even though we technically hide this from non-site admins there isn't much of a reason to hide it from users to allow them to make connections between their own devices.  We need to go over this process much closer before we open it up to just any jack ass first.  For now I will be closing this as I have added in appropriate rights checking to make sure no shenanigans happen from someone knowing the back end code and submitting their own malicious requests.
