### ISSUE TITLE
Support reverse cabinet ordering

### ISSUE THREAD

**Issue by samilliken** [samilliken/openDCIM#526]
Low priority, but it has come up enough times that we need to at least see what is involved in adding the support for this.  Seems to be mostly outside of the US where this comes up, so could just be another cultural difference, but should at least be an option.

Need to decide - should top->bottom versus bottom->top be per cabinet, per data center, or global for the installation?

**Comment by jomigom** [comment]
We do not need this. We number the cabinets from bottom to top. But I understand that someone with a medium DC, and documentation already made (contracts, etc.) will not change this to use openDCIM.

As I've implemented (fac_Config), is a global setting for the entire installation. 

If you want to do it for DC or cabinet, you should add a field in each table corresponding to indicate it. Actually, the most versatile option is to specify it in each cabinet. It is easy in any case.

 

De: Scott Milliken [mailto:notifications@github.com] 
Enviado el: martes, 13 de enero de 2015 13:36
Para: samilliken/openDCIM
Asunto: [openDCIM] Support reverse cabinet ordering (#526)

 

Low priority, but it has come up enough times that we need to at least see what is involved in adding the support for this. Seems to be mostly outside of the US where this comes up, so could just be another cultural difference, but should at least be an option.

Need to decide - should top->bottom versus bottom->top be per cabinet, per data center, or global for the installation?

**Comment by samilliken** [comment]
Let's do it at the Global (default config) level and at the cabinet level - add a field into the fac_Cabinet table for NumberOrder and that's what can be toggled.

**Comment by jomigom** [comment]
Scott,
I have already prepared the changes to close this issue. But I do not know if now is a good time to upload it, or this may affect the release will come out (4.0), despite is set for release 4.1.

**Comment by samilliken** [comment]
Jose,
        Let's hold off until right after I release 4.0.  I think the
reverse ordering is going to take a good bit of testing to make sure that
every use case has been accounted for.

Thanks,
Scott

On Wed, May 13, 2015 at 7:15 AM, Jose Miguel Gomez <notifications@github.com

**Comment by jomigom** [comment]
I leave this issue open until it is tested.
You can define the order in cabinets in general (in config), for each DC or each cabinet
