### ISSUE TITLE
Filter Cabinet ToolTips by User Rights

### ISSUE THREAD

**Issue by samilliken** [samilliken/openDCIM#527]
Stefan reports:

If a user belonging to a specific department logs in, he should only see
cabinets and devices that belong to his department. Basically this
works, meaning, that when he clicks on a cabinet, it's only opened if it
belongs to him.

However, when he just moves the mouse over any other cabinet, the
tooltip that opens shows all defined information of that cabinet,
independent if his deparment is the owner or not.

I suggest to only show the cabinets belongig to it's department already
on the image-map overlay and also on the menu structure, so he's not
even able to see if the cabinet is taken and from whom it's taken. also
he would not be able to open that cabinet by clicking on it or moving
the pointer over it.

I verified this on the opendcim.org/demo site and it does indeed show whatever tooltips are enabled for any user that can log in to the website.

**Comment by wilpig** [comment]
I half assed this check to save on load times.  I'm only checking the owner of the cabinet instead of drilling down to check every device and then giving the highest amount of rights found for everything.

**Comment by samilliken** [comment]
If there is more than one device owner in a cabinet, then it SHOULD be set to General Use, so this is correct behavior.
