### ISSUE TITLE
Cabinet sorting order still not good

### ISSUE THREAD

**Issue by wilpig** [samilliken/openDCIM#528]
![screen shot 2015-01-23 at 11 56 10 am](https://cloud.githubusercontent.com/assets/1653882/5878694/e39c8548-a2f6-11e4-877a-5ba9af8981ea.png)

This is in relation to https://github.com/samilliken/openDCIM/commit/129aa89529e772fda853f5b27a820726476318ab .  Clearly I need to find a better solution because this brought the original problem back.

**Comment by wilpig** [comment]
fiddling with this but it puts all the number only racks at the bottom where I think we're used to them at the top.

ORDER BY Location REGEXP '^[A-Za-z]+$', CAST(Location as SIGNED INTEGER), Location;

**Comment by wilpig** [comment]
I have a fix!  It's gonna seem kinda nutty but it solves this 100%.  We're gonna extend the table row to have a LocationSortable column that will be the Location field minus any spaces and maybe special characters.  When we sort we'll sort on that by LocationSortable alone.  One of the mysql guys at work gave me the idea when he was approached with the problem and he said he would rework the db and tokenize the data.

**Comment by samilliken** [comment]
I'm putting a fork in this one as it appears to be done.
