### ISSUE TITLE
Make adding in environmental sensors easier

### ISSUE THREAD

**Issue by wilpig** [samilliken/openDCIM#531]
![screen shot 2015-01-27 at 12 37 58 am](https://cloud.githubusercontent.com/assets/1653882/5914084/dceca2c8-a5bc-11e4-8e16-a8f7e5f5da4d.png)

Here's the idea I have for adding in sensors, but we need to decouple them from the cabinet first so we can support multiples.  This data could then be tied into the dc/zone maps fairly trivially.

**Comment by wilpig** [comment]
SELECT * FROM fac_Device WHERE TemplateID IN (SELECT TemplateID FROM fac_DeviceTemplate WHERE DeviceType='Sensor')

note for me

**Comment by wilpig** [comment]
There is a flaw in the logic on how we handle sensors and cdu's that will be confusing to end users.  We allow people to specify a device as CDU or Sensor but we only poll via the OIDs on the template.  So a user could make a device a CDU or Sensor without a template but won't be able to poll them.

**Comment by samilliken** [comment]
We'll just need to explicitly add a note to that effect on the page.
