### ISSUE TITLE
import changes from my fork of version 3.3?

### ISSUE THREAD

**Issue by Thermi** [samilliken/openDCIM#533]
Hello maintainers,

I made a fork of openDCIM based on version 3.3 with some new features and changes.
It would be quite nice to have some (or all) of them in some next release.
The git repo is "openDCIM" at my account. You are free to hand pick changes.

This is a short list of the changes:
* Added list for discrete power usage per port for PDUs.
* Fixed some bugs with undefined indexes in arrays.
* Added support for PDUs with three phases, but not using rotary current.
* Added notes and fuses field for PDUs.
* Moved snmp stuff partially out of the seperate functions into the PowerDistribution class.
* Moved handling the processing profiles into a seperate function.
* Made major changes to the way the UpdateStats function works in the PowerDistribution class.

What to come:
* Support for PDUs that are uplinked to other PDUs.

Yes, the code is sometimes not following the style or object oriented style you want to achieve.
I did this at work and my superiors agreed to open source these relatively minor changes.
This version is in productive use at my work place and it would be quite nice to have this migrated upstream, so it's properly maintained.

Kind regards,
Thermi

**Comment by wilpig** [comment]
You are welcome to submit pull requests based off the current dev branch but picking and choosing parts to import will be next to impossible.  We are currently hard at work on version 4.0 and as a result many of these sections have already received a large overhaul.

**Comment by Thermi** [comment]
Okay, I will port my changes to the dev branche and submit a pull request.
