### ISSUE TITLE
Read-only User can "Delete front connections in DataBase"

### ISSUE THREAD

**Issue by adamgent** [samilliken/openDCIM#534]
When a read-only user is logged in, they see all editable fields as greyed out (correctly RO).

However if when viewing a device they click on a path connection to a device (in the "Device Port" Column for the Connections table), they are taken to the Path connections page with the first-hop connection showing.

Under this there is a button "Delete front connections in DataBase" which allows a user to delete the path connection when they should not have permission.

![dcim-patch](https://cloud.githubusercontent.com/assets/10923877/6107597/1f499016-b064-11e4-9e1b-7a5a30ecf80d.png)

**Comment by wilpig** [comment]
OLD!
https://github.com/samilliken/openDCIM/issues/512

**Comment by wilpig** [comment]
Seeing your cabinet menu you will be interested in this though.  https://github.com/samilliken/openDCIM/commit/82dbecc14adb3d8edd2adf6bd14b7912db3d0a8a

**Comment by adamgent** [comment]
Excellent, thanks! :)
