### ISSUE TITLE
mpdf generated reports aren't editable in Adobe Acrobat

### ISSUE THREAD

**Issue by mattbathje** [samilliken/openDCIM#559]

**Comment by samilliken** [comment]
Hrmm.  Interesting to know.  We'll have to keep that in mind for future reports given how simple the solution is.

**Comment by mattbathje** [comment]
Yes, but part of why I tried out a "include-able template" solution for
mpdf reports was so that we hopefully wouldn't have to make changes like
this in more than 1 place. Fixing template_mpdf_reports.include.php fixed
both of the new reports I added (Power Panel Schedule and Cabinet List).

report_supply_status.php had to change separately because I haven't
retrofitted it to use the template (yet) and it is the only other mpdf
generated report so far.
