### ISSUE TITLE
Enhancement: add "Primary Contact" for the virtual servers of VMware ESXi and AIX LPARs?

### ISSUE THREAD

**Issue by spezialist1** [samilliken/openDCIM#571]
Hi all!

I suggest to add the column "Primary Contact" to the table of the virtual servers of VMware ESXi and AIX LPARs. As at the moment, information on the virtual servers is incomplete as contains only "Departmental Owner".

Thanks for the support.

**Comment by samilliken** [comment]
Also hostname since the imagename may not match

**Comment by spezialist1** [comment]
Of course, and this statement is fair and for AIX LPARs.

It would be quite good to add the table also the real hostname list of virtual servers: it is quite implemented both for VMware ESXi and for AIX LPARs.

Very thanks for the support.
