### ISSUE TITLE
Polling of sensors and cdus still has use cases that bomb out

### ISSUE THREAD

**Issue by samilliken** [samilliken/openDCIM#592]

**Comment by spezialist1** [comment]
...And when execute poll_pdu_stats.php from crontab, there is the following messages in root mailbox:

*PHP Notice:  Undefined index: REQUEST_URI in /var/www/openDCIM-master/misc.inc.php on line 98*
*PHP Notice:  Undefined index: HTTP_HOST in /var/www/openDCIM-master/misc.inc.php on line 131*

Very thanks for the support.

**Comment by samilliken** [comment]
That was due to mod_rewrite missing.  This issue has been resolved.
