### ISSUE TITLE
Enhancement for Work Orders

### ISSUE THREAD

**Issue by outdoorbloke** [samilliken/openDCIM#593]
It would be nice if you could create a work order item for specific connections on  a device.

Aka you are installing a new server but you also need to patch it all the way through to a switch that is already installed it would be good if you could individually select the ports on the existing devices (patch panels etc) to be included in the work order

**Comment by samilliken** [comment]
It already does this - if you make a patch connection from end to end, the Export Connections creates a spreadsheet that includes the full path.

Also, it's just a spreadsheet that it creates, so if you only want a subset of the connections, you can delete the rows you don't want.
