### ISSUE TITLE
Hyper V support

### ISSUE THREAD

**Issue by puppetmaster886** [samilliken/openDCIM#614]
Microsoft Hyper V is every day more used on the industry, we had 1/3 of our VM on Hyper V. could you add support to it as well at now is VMware supported?

**Comment by wilpig** [comment]
I'll go ahead and close this because there isn't currently any snmp support for hyper-v or an open api that we can use to get information out of it like we can vmware.

**Comment by samilliken** [comment]
As soon as Microsoft makes the information available via SNMP, or through
some other mechanism that doesn't require installing a no longer supported
library, we can do that.  As it stands, Microsoft really only wants people
to access the information via PowerShell, and through a Windows machine at
that.

-- Scott
