### ISSUE TITLE
getAvailableImages() - wrong path on Windows host

### ISSUE THREAD

**Issue by Gusenichka** [samilliken/openDCIM#618]
preg_match("/api\//",getcwd()) always return false on Windows host.

It's working for me:
preg_match("/api" . preg_quote(DIRECTORY_SEPARATOR) . "/",getcwd())

**Comment by wilpig** [comment]
Can you verify that this works.
```php
if(preg_match(DIRECTORY_SEPARATOR."api".DIRECTORY_SEPARATOR,getcwd())){
```

**Comment by wilpig** [comment]
Also is it giving a list when it passes the check or do I need to adjust the $path to include the directory separator as well?

**Comment by Gusenichka** [comment]
if(preg_match("/api\//",getcwd())){
![image](https://cloud.githubusercontent.com/assets/7326529/8516838/28fde95a-23c2-11e5-8532-d190a3c24627.png)

if(preg_match(DIRECTORY_SEPARATOR."api".DIRECTORY_SEPARATOR,getcwd())){
![image](https://cloud.githubusercontent.com/assets/7326529/8516716/a498f3ae-23c0-11e5-9abd-2d1289ff45fd.png)

if(preg_match("/api" . preg_quote(DIRECTORY_SEPARATOR) . "/",getcwd())){
or
if(preg_match("/api/",getcwd())){
![image](https://cloud.githubusercontent.com/assets/7326529/8516695/5e496942-23c0-11e5-9aec-9bc33bb292f3.png)
