### ISSUE TITLE
Position selector displays incorrect information for half-depth or backside device

### ISSUE THREAD

**Issue by Gusenichka** [samilliken/openDCIM#621]
http://dev.opendcim.org/devices.php?DeviceID=104
![image](https://cloud.githubusercontent.com/assets/7326529/8597336/74b10c2c-265d-11e5-8459-e4c5f36d34c9.png)

Source of the problem: request parameters are case sensitive.

Request in devices.php:
$.getJSON('scripts/ajax_cabinetuse.php?cabinet='+cab+'&DeviceID='+$("#DeviceID").val()+'&HalfDepth='+hd+'&BackSide='+bs, function(data) {

Lets look in ajax_cabinetuse.php:
$dev->BackSide=(isset($_GET['backside']))?($_GET['backside']=='true'?true:false):false;
$dev->HalfDepth=(isset($_GET['halfdepth']))?($_GET['halfdepth']=='true'?true:false):false;

**Comment by wilpig** [comment]
Fixed via @19b6b47
