### ISSUE TITLE
Zero values in table fac_SensorReadings?

### ISSUE THREAD

**Issue by spezialist1** [samilliken/openDCIM#624]
Hi all!

After the made changes are entered in the openDCIM-master, zero values of temperature and humidity in the table fac_SensorReadings?

In what there can be a problem?

**Comment by spezialist1** [comment]
I could define that the reason of this bug in updated the OSS_SNMP/SNMP.php file.
Any ideas?..

**Comment by wilpig** [comment]
I don't understand your question.

**Comment by spezialist1** [comment]
Hi Wilbur,

after made "changing OSS_SNMP to match source" in file OSS_SNMP/SNMP.php a day ago, temperature and humidity sensors reading execute incorrectly: in table fac_SensorReadings inserted the zero values of temperature and humidity.
If return back old version of the file OSS_SNMP/SNMP.php, temperature and humidity sensors reading execute correctly: in table fac_SensorReadings inserted the real values of temperature and humidity.

Very thanks for the support.

**Comment by wilpig** [comment]
I will test on my end again.  I did that before I pushed up the changes and everything returned the same.
