### ISSUE TITLE
Bug of display of the first unit in the cabnavigator?

### ISSUE THREAD

**Issue by spezialist1** [samilliken/openDCIM#626]
Hi all!

In the current release of openDCIM there are two bugs of display of the first unit in the cabnavigator:
1. if the first unit isn't occupied, it is displayed here so ![bug1_1](https://cloud.githubusercontent.com/assets/10425179/8722666/9d4295ee-2bcf-11e5-8bd5-ac28199f8494.png) ;
2. if the first unit is occupied with the device with half depth, it is displayed here so ![bug1_2](https://cloud.githubusercontent.com/assets/10425179/8722667/9e156a1e-2bcf-11e5-8a53-929f238b87af.png) .

Any ideas?
Very thanks for the support.

**Comment by samilliken** [comment]
I think Wilbur already found and fixed this, but apparently didn't enter an issue for tracking on it.

**Comment by wilpig** [comment]
Pretty sure I did too, but that entire function is about to get replaced with the one in testing.



Sent from my Sprint Samsung Galaxy® Note 4.

**Comment by wilpig** [comment]
This has been corrected as part of #526 .
