### ISSUE TITLE
dc_stats and zone_stats: "no data" for temperature, humidity and measured power?

### ISSUE THREAD

**Issue by spezialist1** [samilliken/openDCIM#633]
Hi all!

In file infrastructure.inc.php variables:

$temperature['title']=($titletemp>0)?__("Measured on")." ".$titletemp:__("no data");
$humidity['title']=($titletemp>0)?__("Measured on")." ".$titletemp:__("no data");
$realpower['title']=($titlerp>0)?__("Measured on")." ".$titlerp:__("no data");

always return "no data" value, even Sensors and CDU are normally pulled. For example, the table fac_SensorReadings is completed with the corresponding values of temperature, humidity and last read date.

Very thanks for the support.

**Comment by samilliken** [comment]
I'm not seeing the same issue in my installation.  I'm assuming that you are talking about the tooltips that appear as you hover your pointer over a cabinet.  If so, we will likely need to look at multiple tables to make sure that the relationships between Cabinet / Sensor / Zone / DataCenter are there and correct.

**Comment by spezialist1** [comment]
Here that I assuming (see the attached picture).

Thanks for the support.

24.07.2015 16:38, Scott Milliken <notifications@github.com>
>I'm not seeing the same issue in my installation.  I'm assuming that you are talking about the tooltips that appear as you hover your pointer over a cabinet.  If so, we will likely need to look at multiple tables to make sure that the relationships between Cabinet / Sensor / Zone / DataCenter are there and correct.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/samilliken/openDCIM/issues/633#issuecomment-124522529

--
Чорнобиль форева!

-- реклама -----------------------------------------------------------
Поторопись зарегистрировать самый короткий почтовый адрес @i.ua
http://mail.i.ua/reg - и получи 1Gb для хранения писем

**Comment by samilliken** [comment]
Ok, now that I know what you're referring to I have been able to duplicate it.
