### ISSUE TITLE
Uniq ID of cables

### ISSUE THREAD

**Issue by beermann** [samilliken/openDCIM#635]
Hi,
I would very much like a feature that would create labels on cables that were used in OpenDCIM. So that a uniq label would be generated everytime that you were to patch at connection.

Sune

**Comment by samilliken** [comment]
If you simply want a serialized number, there is already cabling software for that.  There is already an Export Connections feature in openDCIM that supplies the connection information, which is the suggested data for cable labels and is supported by both TIA and BICSI in their recommendations.

**Comment by beermann** [comment]
I know that there are lots of tools to do that, but i do think that when the rest of the information is already in OpenDCIM, then why not the cable ID aswell. I might end up forking OpenDCIM and do it myselft.
