### ISSUE TITLE
API issue - Error when try to post/put device with CustomValues 

### ISSUE THREAD

**Issue by daniellingo** [samilliken/openDCIM#636]
Hey Guys,

I am writing a python script to work with API, it works so well, except not supporting well with CustomValues .

Here is the data I'd like to post 
~~~
{'v3PrivProtocol': 'DES', 'TemplateID': 8, 'PowerSupplyCount': 2, 'Cabinet': 2, 'InstallDate': '2015-07-26', 'Rights': 'Write', 'CustomValues': "'2' => 'live'", 'Label': 'STAD0094', 'v3SecurityLevel': 'noAuthNoPriv', 'v3AuthProtocol': 'MD5', 'WarrantyExpire': '1970-01-01', 'DeviceType': 'Server', 'SNMPVersion': '2c', 'Owner': 2, 'Position': 11, 'Height': 1, 'Ports': 4, 'MfgDate': '1970-01-01'}
~~~

The following is the error I saw, 
~~~
Slim Application Error
The application could not run because of the following error:

Details

Type: ErrorException
Code: 8
Message: Array to string conversion
File: /var/www/html/openDCIM-4.0.1/logging.inc.php
Line: 240
Trace

#0 [internal function]: Slim\Slim::handleErrors(8, 'Array to string...', '/var/www/html/o...', 240, Array)
#1 /var/www/html/openDCIM-4.0.1/logging.inc.php(240): PDOStatement->bindParam(':OldVal', 'Array')
#2 /var/www/html/openDCIM-4.0.1/logging.inc.php(204): LogActions->WriteToDB()
#3 /var/www/html/openDCIM-4.0.1/assets.inc.php(1803): LogActions::LogThis(Object(Device), Object(Device))
#4 /var/www/html/openDCIM-4.0.1/api/v1/index.php(846): Device->UpdateDevice()
#5 [internal function]: {closure}('9')
#6 /var/www/html/openDCIM-4.0.1/Slim/Route.php(468): call_user_func_array(Object(Closure), Array)
#7 /var/www/html/openDCIM-4.0.1/Slim/Slim.php(1338): Slim\Route->dispatch()
#8 /var/www/html/openDCIM-4.0.1/Slim/Middleware/Flash.php(85): Slim\Slim->call()
#9 /var/www/html/openDCIM-4.0.1/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
#10 /var/www/html/openDCIM-4.0.1/Slim/Middleware/PrettyExceptions.php(67): Slim\Middleware\MethodOverride->call()
#11 /var/www/html/openDCIM-4.0.1/Slim/Slim.php(1283): Slim\Middleware\PrettyExceptions->call()
#12 /var/www/html/openDCIM-4.0.1/api/v1/index.php(1116): Slim\Slim->run()
#13 {main}
~~~

Any input will be appreciated! :)

**Comment by wilpig** [comment]
There isn't a deviceid to update with a post operation. You should be trying a put operation. What url did you attempt to post to?



Sent from my Sprint Samsung Galaxy® Note 4.

**Comment by wilpig** [comment]
Also updating the custom values isn't currently supported.



Sent from my Sprint Samsung Galaxy® Note 4.

**Comment by wilpig** [comment]
And now that i've got a keyboard in front of me, you've put in an array definition in the middle of a json string.  If it were taking json input it would need to be like "CustomValues":{"2":"123"}.

The current plan is to extend the device model with the names of the fields in the CustomValues so that you can update them directly.  This is going to require a few changes to make work, watch the email list and we'll announce when we've made them.

**Comment by briantilburgs** [comment]
Hi there,
I'm already trying for a Day to send some info to opendcim, but no result.
for instance a new user:
curl -k  -u "user:pass" -H "Content-Type: application/json" -X PUT -d '{"UserID":"newuser","LastName":"newlast","FirstName":"newlast","Phone1":"0031612345678","Phone2":"","Phone3":"","Email":"","AdminOwnDevices":"","ReadAccess":1,"WriteAccess":1,"DeleteAccess":1,"ContactAdmin":1,"RackRequest":1,"RackAdmin":1,"SiteAdmin":1,"Disabled":0}' https://opendcim.org.local/api/v1/people/newuser

can anybody help me?

Thanks,
Brian

**Comment by samilliken** [comment]
Please subscribe to the discussion mailing list and post questions there.
The issue list on GitHub is only for active issue tracking.

http://list.opendcim.org/listinfo/discussion


Scott
