### ISSUE TITLE
As it is correct to calculate the used space in cabinets?

### ISSUE THREAD

**Issue by spezialist1** [samilliken/openDCIM#651]
Hi all!

As it is correct to calculate the used space in cabinets? For example, in files ajax_tooltip.php and cabnavigator.php the call is used:

$used=$cab->CabinetOccupancy($cab->CabinetID);

where class Cabinet::CabinetOccupancy() (from assets.inc.php) is:

//JMGA halfdepth height calculation
$sql = "select sum(if(HalfDepth,Height/2,Height)) as Occupancy from fac_Device where ParentDevice=0 AND Cabinet=$CabinetID";

In my opinion it is correct. Used space it is correctly displayed in cabnavigator and on the tool tips on drawings of zones and DCs.

But in the infrastructure.inc.php file the used space is calculated as:

$metrics = CabinetMetrics::getMetrics( $cabRow->CabinetID );
$used=$metrics->SpaceUsed;

where class CabinetMetrics::getMetrics->SpaceUsed (from assets.inc.php) is:

$sql = "select sum(a.NominalWatts) as Power, sum(a.Height) as SpaceUsed, sum(b.Weight) as Weight from fac_Device a, fac_DeviceTemplate b where a.TemplateID=b.TemplateID and Cabinet=:CabinetID and HalfDepth=0";

In my opinion it is not correct. And how to be with devices with the half depth? And because of it used space color it is displayed on drawings of zones and DCs doesn't coincide with color of the used space displayed in cabnavigator and on the tool tips.

Very thanks for the support.

**Comment by samilliken** [comment]
No, it is a known issue that I thought we already had an open GitHub issue on, but apparently not.  I've been working on it this week.

Half depth items will likely be ignored in the calculations.  The SQL to determine whether or not there are 2 x half depth devices on the same U markers would be extremely detrimental to performance in large scale installations, so half depth will simply be treated as empty.

One other option that we are debating is doing a "full calculation" of the metrics every time the Device::UpdateDevice routine is called and write that to a cabinet metrics table, which would simply be queried when we pull statistics - thereby eliminating the performance hit of checking every cabinet every time.

**Comment by spezialist1** [comment]
I perfectly understand all this, but above the specified debate and reflections are carried out so far, can be to make a calculation of the used space in all three files ajax_tooltip.php, cabnavigator.php and infrastructure.inc.php absolutely identical? For example, I consider that in the infrastructure.inc.php file it is necessary to calculate the used space as well as in the ajax_tooltip.php and cabnavigator.php files.

At least it will prevent a __real__ situation when in different places of openDCIM in the same cabinet different value (color) of the used space is displayed.

Very thanks for the support.

**Comment by samilliken** [comment]
Yes, I am verifying that we are consistent in the way that space is calculated in all three areas.  CabinetMetrics::getMetrics no longer has a space calculation in it, so that is a moot point.

**Comment by samilliken** [comment]
Ok, I've changed my mind on this.  I'm going to make the CabinetMetrics::getMetrics() routine work the same way as in the ajax_tooltips.  I don't think either method will give a truly accurate view, but in terms of providing raw metrics, I agree that Jose's method of calculation is probably better.

**Comment by spezialist1** [comment]
Ok Scot, thanks for understanding of our problem :-).

P.S.: I think, testing of new release of openDCIM 4.1 will be successful.
