### ISSUE TITLE
PUE_DCEM integration

### ISSUE THREAD

**Issue by MorinPierre** [samilliken/openDCIM#652]
Hi, 

Are you planning to add the pue-test branch to the main branch? I won't be able to help you after the end of August so it would be great to do it before (if you want to do it).

**Comment by wilpig** [comment]
There is a lot of code there to evaluate before we consider merging it with the main branch.

**Comment by MorinPierre** [comment]
Ok, I understand. If I can help you, tell me.
Do you receive the mails I send in the discussion list? I didn't get any answers for a while. I can understand that you are busy, I just want to know if anybody receives them.

**Comment by wilpig** [comment]
Yes I have seen them, I just don't respond if I have nothing to add.  If you have noticed I have pulled in all your changes and made sure that branch has been kept up to date with the changes we're making there.  I'm very consumed with other tasks at the moment and this is more back burner.

**Comment by MorinPierre** [comment]
Ok, thank you for your answers.
