### ISSUE TITLE
bug on label entry 4.0.1

### ISSUE THREAD

**Issue by skprog** [samilliken/openDCIM#661]
using version 4.0.1 from 3.3 when editing a device in the rack. that has no template. that is marked device type cdu. the label does not pull in. though it will still assign. the label does not show up even though i have it in rack view

**Comment by skprog** [comment]
also when doing reports the images for said devices seem to come up with no label.

**Comment by wilpig** [comment]
There are no images on any reports with labels.

**Comment by skprog** [comment]
i mean the jpeg that gets constructed. report_network_map.php ends up showing me an awesome diagram.  but some of my servers are missing names. as in its just a blank circle. 
![untitled](https://cloud.githubusercontent.com/assets/4402778/9137826/530a075c-3cee-11e5-9820-39716eb4e73c.png)

**Comment by skprog** [comment]
here is a shot of the label issue. that same issue crops up in the reporting section of the config area. 

![untitled2](https://cloud.githubusercontent.com/assets/4402778/9173361/a41f75cc-3f47-11e5-8412-8fde43d413bd.png)

**Comment by samilliken** [comment]
It sounds almost as if the CDU and device tables didn't get the foreign keys linked properly during upgrade.

**Comment by skprog** [comment]
in sql right now checking.

**Comment by skprog** [comment]
major amounts of ports are messed up or null as well. in sql. given this info i am reverting to a previous state.

**Comment by skprog** [comment]
i consider this a closed case as the upgrade was possibly not done correctly. as i am new to this software.
