### ISSUE TITLE
cabnavigator doesn't display devices

### ISSUE THREAD

**Issue by MorinPierre** [samilliken/openDCIM#670]
Hi there,

My cabnavigator and row view display empty cabinets. I checked the DB I still have my devices. Does the problem come from your recent modification or am I the one who broke everything?

**Comment by wilpig** [comment]
Odds are you have a javascript error or something related to the api.  I'll leave this open in case you've found an edge case that I didn't test.

https://github.com/samilliken/openDCIM/issues/526

**Comment by MorinPierre** [comment]
I think you forgot to change the URL in the 1094th line of scripts/common.js. Things work better with mine.
