### ISSUE TITLE
SNMP get vs walk

### ISSUE THREAD

**Issue by wilpig** [samilliken/openDCIM#672]
I've hit a case with an Eaton CDU that it would not respond to an snmpget but it will a walk.  We might need to put a fall back on the snmp function to try a get first and if that fails to try a walk before it declares failure.

```
[pig@firewall mrtg]# snmpget -v 1 -c pig 10.0.0.9 .1.3.6.1.4.1.534.6.6.7.7.1.1.4.0
Error in packet
Reason: (noSuchName) There is no such variable name in this MIB.
Failed object: SNMPv2-SMI::enterprises.534.6.6.7.7.1.1.4.0

[pig@firewall mrtg]# snmpwalk -v 1 -c pig 10.0.0.9 .1.3.6.1.4.1.534.6.6.7.7.1.1.4.0
SNMPv2-SMI::enterprises.534.6.6.7.7.1.1.4.0.1 = INTEGER: 755
```

**Comment by samilliken** [comment]
That's because you're attempting to get the wrong OID.  Look at your
results - when you do the walk, it returns the child of the tree that you
requested, rather than the exact OID.  snmpget is working as expected.


Scott

**Comment by wilpig** [comment]
And this is why I shouldn't do shit late at night.  I miss the little crap.
