### ISSUE TITLE
Template cloning: data ports and power ports aren't cloned?

### ISSUE THREAD

**Issue by spezialist1** [samilliken/openDCIM#673]
Hi all!

I want to tell, that from openDCIM version 3.1 and on the current version on GitHub, the following bug is still not corrected in case of cloning templates of devices: data ports and power ports aren't cloned. I.e., corresponding tables of ports the absolutely empty.

Very thanks for the support.

**Comment by wilpig** [comment]
Not a bug. It's been explained in the mailing list plenty of times.  Close #673



Sent from my Sprint Samsung Galaxy® Note 4.
