### ISSUE TITLE
Can't assign contact for departement in install.php

### ISSUE THREAD

**Issue by actatux** [samilliken/openDCIM#674]
Hi,

I'm trying to install a new openDCIM instance. In the installer, I have been able to create a new department. However, I can' assign any contact in https://localhost/install.php?dept&preflight-ok. Every time I click on "Assign Contact", the install.php page is loaded into the iframe "groupadmin", below the form.

In install.php, line 2038, the onClick action is showgroup($dept->DeptID).
Line 1965, showgroup() open the "groupadmin" iframe at location dept_groups.php?deptid=$dept->DeptID

When loading this location in the web browser, I'm redirected to install.php.

I found out that dept_groups.php requires misc.inc.php (through facilities.inc.php).

In misc.inc.php:
```php
 768 if(isset($devMode)&&$devMode){
 769         // Development mode, so don't apply the upgrades
 770 }else{
 771         if(file_exists("install.php") && basename($_SERVER['PHP_SELF'])!="install.php"      ){
 772                 // new installs need to run the install first.
 773                 header("Location: ".redirect('install.php'));
 774                 exit;
 775         }
 776 }
```

Obviously, the installer is trying to call another location in vain, being permanently redirected to itself.

**Comment by wilpig** [comment]
While I will acknowledge that is a bug but the bigger bug here is you cannot create a user in the install process so the assign contacts button showing is the real bug.

**Comment by actatux** [comment]
Should you remove showgroup() function as well? It looks like dead code now.

**Comment by actatux** [comment]
What a cleaning! Thanks wilpig. ;-)
