### ISSUE TITLE
Support ISO 8601 style dates (YYYY-MM-DD)

### ISSUE THREAD

**Issue by hawson** [samilliken/openDCIM#697]
The US date convention of M/D/Y is pretty confusing, and the ISO 8601 standard (YYYY-MM-DD) is preferred and used in a lot of places.  Ideally, ISO 8601 should be used everywhere, but this is probably better set as a config option.  Note that this would only affect input and display:  the internal date storage in the DB can (probably) use the internal date formats.

**Comment by wilpig** [comment]
There's already an issue for this

**Comment by wilpig** [comment]
#83

**Comment by hawson** [comment]
Ah, so I see.  Duplicates  #83

**Comment by wilpig** [comment]
Yeah. we're aware of it and acknowledge the problem but fixing it isn't high priority or easy.
