### ISSUE TITLE
Open tree navigation when you navigate through the maps

### ISSUE THREAD

**Issue by olivierbeytrison** [samilliken/openDCIM#705]
would it be possible to expand the navigation tree on the left while you navigate through the maps ?

**Comment by wilpig** [comment]
I don't understand what you're asking, explain with examples.



Sent from my Sprint Samsung Galaxy® Note 4.

**Comment by olivierbeytrison** [comment]
When I navigate through the containers using the map to find my Datacenter, the navigation tree on the left doesn't expand to display where I am in the tree.

See this video : https://www.youtube.com/watch?v=Vb8B2ZoulRs

**Comment by wilpig** [comment]
They should be opening now.  You might have a javascript error going on that I can't see.

http://dev.opendcim.org/dc_stats.php?dc=1

login / pass  : dcim / dcim

**Comment by wilpig** [comment]
<img width="1367" alt="screenshot 2016-01-08 07 36 17" src="https://cloud.githubusercontent.com/assets/1653882/12199025/891318c4-b5da-11e5-906c-67ac45b72f06.png">

**Comment by samilliken** [comment]
Are you running this on 4.0.1 release or is this from github master?  I believe that this was resolved between the last release and the current master.

**Comment by olivierbeytrison** [comment]
I'm running a github master release from beginning of December.
last commit I have is d3a691ab64576b438f7e1655a94a99de63c7580d

I don't have any error in the js console though. Just a warning from Chrome about jquery.min (Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/)

I'll try to pull from master and see if it changes

**Comment by olivierbeytrison** [comment]
ok I get it now ....
while you move through containers the tree won't change ... but indeed, as soon as you reach a DataCenter it will expend to display the content of the DC.

**Comment by olivierbeytrison** [comment]
Eh! thanks! that's what I was doing on my side :p
works perfectly :)
