### ISSUE TITLE
in pue-test branch, mechanical_devices.php requires a zone

### ISSUE THREAD

**Issue by mattbathje** [samilliken/openDCIM#706]
The Infrastructure Management -> Edit Mechanical Devices page requires the Zone attribute be filled in. On our environment, where only 1 datacenter has Zones defined, it is defaulting the zones for any data center to be the ones from the other, incorrect datacenter.

**Comment by wilpig** [comment]
We'll be looking at the pue-test stuff after 4.1 goes out.  We won't be doing a direct merge but picking and choosing what to merge.

**Comment by samilliken** [comment]
There's too much difference between the pue-test and master branches and they can't be merged at this point, so basically we'll be picking and choosing what to migrate.  Therefore, this issue isn't really valid.
