### ISSUE TITLE
Cabinets aren't showing computed watts or weight

### ISSUE THREAD

**Issue by wilpig** [samilliken/openDCIM#711]
Duh huh, I forgot to update that when I changed the device loading module over to ajax.  This one is pretty important.

**Comment by wilpig** [comment]
@samilliken Do you still have the formula for figuring moment and the center of gravity?

**Comment by samilliken** [comment]
https://github.com/samilliken/openDCIM/blob/4.0.1/cabnavigator.php

It's in the loop that builds the cabinet.  Line 277

**Comment by wilpig** [comment]
Okay.  I'm gonna have to rethink that because that won't work now.  Since we can have inverted cabinets it needs to keep that in mind to find the height.
```
$totalMoment+=($DeviceTotalWeight*($device->Position+($device->Height/2)));
```

**Comment by samilliken** [comment]
Also look at line 347 where it uses the moment to calc center of gravity.

Scott

**Comment by wilpig** [comment]
damnit.  this isn't gonna have the children's weight as part of the parent device.  what a pain in the ass.

**Comment by wilpig** [comment]
and device weight isn't part of our device model either. I'm really gonna have to think about this more.
