### ISSUE TITLE
sensor with custom OID

### ISSUE THREAD

**Issue by xamulap** [samilliken/openDCIM#713]
Would it be possible to add in sensor SNMP Configuration custom OID ?

**Comment by wilpig** [comment]
This is the type of thing we typically answer on the mailing list and not here.  What type of sensor and to what end?  You can already add in sensors under the templates and you can put the oid there.

**Comment by xamulap** [comment]
I meant it like feature request. I have specific temperature sensors and every one of them use different OID, I know I can create template for each of them but is is not best solution, number of sensors will grow.  May by I can try to do it myself if this kind of feature is not in roadmap.
