### ISSUE TITLE
Triple-dash is invalid comment in mysql 5.5 (4.1 release download)

### ISSUE THREAD

**Issue by mnibbelink** [samilliken/openDCIM#720]
Unsure if you'd like me to push a patch for this in github, but it's a simple fix

--- this is an invalid comment in mysql
-- this is a valid comment

The last 3 table creation comments in "create.sql" are syntax errors in mysql 5.5.  They should be converted to "--"

    mitch@vm-mitch:~/src/openDCIM-4.1$ grep -e "---" create.sql
    ---
    --- Table structure for fac_DeviceCustomAttribute
    ---
    ---
    --- Table structure for fac_DeviceTemplateCustomValue
    ---
    ---
    --- Table structure for fac_DeviceCustomValue
    ---
    mitch@vm-mitch:~/src/openDCIM-4.1$

    mitch@vm-mitch:~/src/openDCIM-4.1$ mysql -v -udcim -pdcim dcim < create.sql
    [...]
    
    --------------
    -
    -
    -
    DROP TABLE IF EXISTS fac_DeviceCustomAttribute
    --------------
    
    ERROR 1064 (42000) at line 843: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-
    -
    -
    DROP TABLE IF EXISTS fac_DeviceCustomAttribute' at line 1
    mitch@vm-mitch:~/src/openDCIM-4.1$

**Comment by wilpig** [comment]
Closed by commit @3bbf44706c879b46e487cb7931c8b310da654579
