### ISSUE TITLE
Power connection gets removed from device when clicking the update button

### ISSUE THREAD

**Issue by olivierbeytrison** [samilliken/openDCIM#722]
Hello,

Just hit a weird bug. When setting the power connection on a device, they are correctly set in the DB when pushing the "Save" button at the end of the power connection row.

But if after that you hit the "Update" button for the device, those power connections are removed.

Running on commit 1540623a0dd568eb2776da88f848805f0479b207

**Comment by olivierbeytrison** [comment]
I just upgraded to the latest master commit and the bug still occur.

**Comment by samilliken** [comment]
Ok, there's a simple fix for this - don't make any mistakes when you enter
a device.

Heh, no, I've been able to recreate the issue.  Looking into it.

-Scott

On Mon, Jan 25, 2016 at 2:30 AM, Olivier Beytrison <notifications@github.com

**Comment by olivierbeytrison** [comment]
Thanks for the quick fix ! works very well :)
