### ISSUE TITLE
Connection path incorrectly displayed in certain conditions

### ISSUE THREAD

**Issue by olivierbeytrison** [samilliken/openDCIM#724]
In some condition, when a connection path is not yet fully connected between two devices, the path is incorrectly displayed.

Example below, obtained by clicking on the Port 5 from Patch Panel "PP-FO-PER80-A30.245-02-H22"
![image](https://cloud.githubusercontent.com/assets/2838126/12557253/153dadac-c38a-11e5-87b2-0a9408475aa8.png)

For the same link, but on device "MDS FAB B" clicking on the port gives the correct output
![image](https://cloud.githubusercontent.com/assets/2838126/12557325/85664576-c38a-11e5-9c75-628faf7e5294.png)

Please give guidance if you need some output from the DB or other kind of debug

**Comment by wilpig** [comment]
It's a layout glitch.  Note the open pipe on the left side of the first image.

**Comment by olivierbeytrison** [comment]
Not sure it's a browser issue tbh. Tried with Chrome FF IE all render the same way (well ok IE isn't really a good example :D )

You'll find the html code in this [GIST](https://gist.github.com/olivierbeytrison/ce84e94324d0f1a6a93a)

**Comment by wilpig** [comment]
```
	<td>&nbsp;&nbsp;&nbsp;</td>
		<td class="right"></td>
		<td></td>
		<td class="f-right"></td>
```

It looks to me that the browser is just collapsing this into nothing and shifting that first cell over to the left.  If you can recreate this in my dev instance or get me access to yours to troubleshoot further I can do something about it.

**Comment by olivierbeytrison** [comment]
alright, on your test instance, go to http://dev.opendcim.org/devices.php?DeviceID=4864
click on the right on "Port1(Rear)" and the same happen

![image](https://cloud.githubusercontent.com/assets/2838126/12605825/bbf421aa-c4c8-11e5-9e11-1b7453cc65f9.png)


this has to do when you use chassis for fibers/coppers it seems

**Comment by olivierbeytrison** [comment]
btw in the Path div it should display "Port 1 (Rear)" instead of "Port -1" ;)

**Comment by wilpig** [comment]
Looks like the root cause of this is because the patch panel is inside of a chassis and that routine was never designed for that case.

**Comment by wilpig** [comment]
Tested with non-nested patch panels and seeing correct results.  Marking this closed.

**Comment by olivierbeytrison** [comment]
just pulled master. so far the bug is gone, and I tried a dozen of different kind of paths and no side effects so far.

Thx for the job !
