### ISSUE TITLE
installer.userconversion.inc.php is missing opening <?php header

### ISSUE THREAD

**Issue by mattbathje** [samilliken/openDCIM#727]
installer.userconversion.inc.php is missing opening <?php header - this is causing it to throw a 500 error during an upgrade from 3.3 to 4.1.

**Comment by wilpig** [comment]
Weird.  it shouldn't need that in the case of an import, glad you found the bug.

**Comment by mattbathje** [comment]
Wonder if it is related to PHP version - are stuff is still running on 5.3.3
