### ISSUE TITLE
Ability to use dynamic maps pulled from external location

### ISSUE THREAD

**Issue by s-williamson** [samilliken/openDCIM#736]
I work for a mining company and we have many different sites. We have regular Ariel photography taken which is available for us to use via a http link. Within "Containers" there is a field called "Drawing URL" which just points to an image within a folder. 

Would it be possible to have it pull an image from a http or http source to which we could then add the X,Y locations to?

As an example Drawing URL = https://www.google.com.au/maps/@-25.8137546,135.6329167,4.97z/data=!5m1!1e4

(We don't use Google maps but that's just an example)

**Comment by s-williamson** [comment]
Just to add to this, some GIS people within our organisation said for open source look at a site called Leaflet - http://leafletjs.com/ which would assist if this is a feature that could possibly be added.

**Comment by wilpig** [comment]
No this isn't possible because google maps and the like use embedded iframes and not actual images.  The way that the images are drawn on the various status screens is through the use of a canvas that cannot handle dynamic content.
