### ISSUE TITLE
panel schedule fixes and enhancements

### ISSUE THREAD

**Issue by mattbathje** [samilliken/openDCIM#737]
- power panel schedule report isn't displaying the power source
- modify panel schedule report to show parent panel when displaying a sub panel
- power panel schedule report isn't displaying if there are multiple levels of parent for a panel
- modify power panel schedule (on report and on panel edit page) to display sub-panels in the schedule
- modify panel edit page to show cdus/sub-panels that are associated with the panel, but not assigned a breaker as "unscheduled"

**Comment by wilpig** [comment]
That last point, there is an error procedure for that which could hold those.  IIRC it makes a box underneath the panel and says something about cannot draw them.

**Comment by samilliken** [comment]
Is there still an open issue with this or not?
