### ISSUE TITLE
Custom Device Attributes

### ISSUE THREAD

**Issue by cdcrawford** [samilliken/openDCIM#742]
When attempting to save a device with a custom device attribute the value is cleared upon refresh.

the Log on the device shows as follows:
2016-03-01 15:20:42	USER  InsertCustomValue <BLANK> => <BLANK>

I attempted to store 55000.00 in the field, which is defined as a string.

**Comment by cdcrawford** [comment]
Any logs or data you would like, I can likely get you.

**Comment by wilpig** [comment]
What version are you running?

**Comment by cdcrawford** [comment]
We're running the GA (4.1.1?) with some asset.inc.php changes for empty racks, PDU issues and another change. Minor.

**Comment by wilpig** [comment]
I found a bug in how the custom values are getting logged but they are getting written to the database just fine.

**Comment by cdcrawford** [comment]
Thanks Wilbur, that was a quick turn around, I appreciate it!

Do you have a commit number or change that I can implement on our install as an interim fix until 4.2?
