### ISSUE TITLE
Template Manufacturer's Not Matching

### ISSUE THREAD

**Issue by xcezzz** [samilliken/openDCIM#743]
With a fresh install of openDCIM (from GIT). I pulled in some templates. It seems that some most of them are pulling odd ManufacturerIDs... Even many templates that were "pulled" from Dell, are showing as two different Manufacturer names... SpectraLogic/Wrightlne

The SuperMicros look right though. The Synaccess should be APC.

![screen shot 2016-03-03 at 11 22 18 am](https://cloud.githubusercontent.com/assets/1828125/13500826/38b75812-e132-11e5-9d46-02933ad86424.png)

**Comment by wilpig** [comment]
Your manufacturers are out of sync.  This wasn't a clean install.

**Comment by wilpig** [comment]
<img width="1143" alt="screenshot 2016-03-03 10 30 47" src="https://cloud.githubusercontent.com/assets/1653882/13501121/07a1ee56-e12b-11e5-8159-0221e7fd552c.png">

**Comment by xcezzz** [comment]
Thank You, figured something was wrong.

But I am curious since I haven't gotten too deep into the code.  

Wouldn't the "insert id" be a strange way of referencing something global to all installs. 
Should they not reference the global ID? My fork I played with putting it on the GlobalID, and that was easily able to resolve all the offset ones I have. 

Will reset and retry though.

**Comment by wilpig** [comment]
You shouldn't have been able to pull any templates using the UI without getting the manufacturers set first.  Not sure how you get in that situation.

**Comment by xcezzz** [comment]
Was a fresh install from master. The manufacturers are listed in there right and all gids match yours. However the insert ID'S they are using are totally different.

**Comment by wilpig** [comment]
The local IDs don't matter.  They are supposed to be flexible because the will change from install to install.  The install is going to be local centric with the option of being able to be associated with a global match from the repo.

**Comment by wilpig** [comment]
Goto the #opendcim on freenode for more information.
