### ISSUE TITLE
Manufacturer IDs seem to be able to get out of sync from repo_sync.php

### ISSUE THREAD

**Issue by samilliken** [samilliken/openDCIM#744]
Reported on IRC

**Comment by samilliken** [comment]
Need details about how this has happened.  Have tried to recreate and was unable to make it happen, so even though I've seen it manifested, just don't know how they got there.

**Comment by wilpig** [comment]
Steps to make it manifest, but I haven't tested.

1. Clean install of 4.1.1
2. Click the sync button in the installer, maybe two or three times for good measure
3. Goto the sync UI and try to import a device

**Comment by crashcartpro** [comment]
1. Clean install of 4.2 (git clone on 5/4/2016)
2. Go through installer, click the "sync" button once on the "complete" tab.
3. Navigate over to "Template Management" > "Repository sync"
4. Get Template list
5. Start pulling templates from APC, Dell, HP, Cisco
6. Switch to edit device templates. 
7. the "template" drop down box is showing devices with the wrong manufacturers.

APC => Rittal
DELL => Quantum
HP => Symphony
Cisco => Rittal

**Comment by crashcartpro** [comment]
1. Clean install of 4.2 (git clone on 5/4/2016)
2. Go through installer, did NOT click the "sync" button.
3. Navigate over to "Template Management" > "Repository sync"
4. go to "Sync Manufacturers" and select APC, Dell, HP, and Cisco
5. Start pulling templates from APC, Dell, HP, Cisco
6. Switch to edit device templates.
7. the "template" drop down box is showing devices with the correct manufacturers.

so far, so good.
