### ISSUE TITLE
How can insert desktop server or blade?

### ISSUE THREAD

**Issue by naechin91004** [samilliken/openDCIM#746]
Hello.

I can't add blade server or desktop server.

How can add blade or desktop?

Plz help me

**Comment by wilpig** [comment]
1) Use the mailing list for requests like this.
2) To put a desktop in a rack, you shouldn't, but if you insist there is a tray you can pull from the device repo under the generic devices
3) To put a blade in you have to make a blade chassis first, look under the templates.

**Comment by wilpig** [comment]
cl
