### ISSUE TITLE
PathMaker doesn't work with 2 Patch Panel beetween the two same Rack

### ISSUE THREAD

**Issue by sgaiotti** [samilliken/openDCIM#750]
Hello

i try to make connection between 2 devices in two racks and i have 2 patch panel between these rack : 1 for fiber and 1 for RJ45
I have the message "Path not initialized" (it's work if I unconnect Fiber Patch Panel)

thanks in advance

**Comment by samilliken** [comment]
Yeah, not really an issue.  If you have multiple paths, you'll have to navigate it yourself.

**Comment by sgaiotti** [comment]
Hello

Thanks for your answer
I think I'll use the following workaround : create a big patchpanel (including the both)

Regards

Stéphane Gaiotti
