### ISSUE TITLE
Date is show in wrong format

### ISSUE THREAD

**Issue by WoMec** [samilliken/openDCIM#756]
Hi, I know that openDCIM supports ISO 8601 style dates but when I editing devices, date is shown in mm/dd/yyyy format. 

Is it possible to show date in ISO format ( yyyy/mm/dd ) ? 

Thanks

**Comment by wilpig** [comment]
It's on my list to eventually put all dates in ISO 8601 but it isn't high on the list.

**Comment by WoMec** [comment]
OK, thx for resp.
