### ISSUE TITLE
Problem adding sensors?

### ISSUE THREAD

**Issue by jcasals** [samilliken/openDCIM#759]
Hello,

I am from PIC, a research center in Barcelona, and we just started using openDCIM. We are adding racks, server, etc, and we wanted to test sensor via SNMP., but we seem to not be able to make it work, and we are not sure if it's us, or a bug.

The process we did is: we created a sensor template and then we add to the Environmental Sensors a new device using this template.

In the SNMP configuration, the Test SNMP button, returns values that give us the hint that this should be working. From command line, SNMPGet and these same OIDs we assigned to the sensors in the openDCIM portal, give us the right values.

For instance, our command line output of the snmpget for the temperature is the following:
```
[user@host ~]# snmpget -c public -v2c 192.168.1.5 .1.3.6.1.4.1.5528.100.4.1.10.1.8.2628357572
SNMPv2-SMI::enterprises.5528.100.4.1.10.1.8.2628357572 = INTEGER: 31
```

And when we put it on the template, the value of the sensor is zero.

Do you know if we are doing something wrong? Or this could be a bug?

We are using the 4.2 version.

Thank you in advance,

Jordi.

**Comment by wilpig** [comment]
We prefer for support questions to goto the mailing list.

Make sure that your template has the checkmark next to managed. Then see the wiki for setting up the background cron jobs that actually do the poling.



Sent from my Sprint Samsung Galaxy® Note 4.
