### ISSUE TITLE
Adding additional Device Types in Templates

### ISSUE THREAD

**Issue by longshot902** [samilliken/openDCIM#767]
Could it be possible to add additional device types to new template creations?
I'm looking for the following items: Routers, Line Cards, Tape Libraries, and Card Modules.

Or is there another recommended way to handle this?

**Comment by wilpig** [comment]
NO!  Read the faq.  http://opendcim.org/faq.html

A router is either going to be an application server or a fancy switch.
Line card, application server, server, or switch.
Tape library, well you have a point that it's a weird device but it's just a fancy application server.
Card modules, see line card.

**Comment by Kilowatt-W** [comment]
I hve looked at the source code and found it very easy to add some more types in the need to document our Firewalls and Tape Libraries.

Why should it be not possible to add some more types ?

Greetings

Wolfgang

**Comment by wilpig** [comment]
How is a firewall not a type of switch or an appliance?  And your tape library not a server or appliance?



The other types are unecesssary.

**Comment by Kilowatt-W** [comment]
Hi it would be for better information in datacenter if you have different groups of people working there with different types of devices.

So firewaller can manage there devices and you can report.

If nobody wants it its ok for me.

**Comment by wilpig** [comment]
You can set tags on devices if you want to specify custom types like that.  The primary device types cover everything acceptably currently.
