### ISSUE TITLE
Edit Cabinets, multiple cabinets with same name at different facilities

### ISSUE THREAD

**Issue by dcninja** [samilliken/openDCIM#772]
When selecting "edit cabinets" you are presented with a drop down of all cabinets in Database. This does not make identifying cabinets easy when you use the same naming convention in each site. Would it be possible to select the DC first on this page and then the page refreshes with the cabinets within that site, or place the DC prefix within the cabinet field.

**Comment by wilpig** [comment]
![screenshot_20160520-055151](https://cloud.githubusercontent.com/assets/1653882/15425624/0849606c-1e4f-11e6-8bc2-4175c293ce2e.png)

That's already an option

**Comment by wilpig** [comment]
There's already a option to add the DC name.
