### ISSUE TITLE
Error Calculating Available RU on DC Summary Page

### ISSUE THREAD

**Issue by s-williamson** [samilliken/openDCIM#774]
HI

One of our Datacentres is showing
                        Infrastructure	Occupied	Allocated	Available
Total U 1527	1120	          487	  135	  -215
Percentage	73.3%	         31.9%	   8.8%     -14.1%

The total U figure is correct (33 racks of 45RU and 1 rack 42RU)
Its saying there is 1120+487+135 items within the racks (1742) leaving -215 slots
I did a SQL Query to get the row height from every item in the DC and came up with a figure of 1760.
We have a lot of CHASSIS in our DC full of Blades. I'm not 100% certain where the error in calculation is but I'm guessing that both Chassis Height and Blade height is being added? Maybe things that are half depth are (and located at the rear) are being calculated?

SQL Query for your reference.

select Height from fac_Device as De  inner join fac_Cabinet AS cab ON De.Cabinet = cab.CabinetID   where cab.DataCenterID = 4;

**Comment by s-williamson** [comment]
Also a Nice to have, at the DC Summary Page, if one of the reporting fields could be "Reservations" as we use the reservation feature quite a bit to future work and capacity planning. Thanks again.

**Comment by samilliken** [comment]
Allocated = Reserved

**Comment by s-williamson** [comment]
Thanks Scott.
