### ISSUE TITLE
FPDF error

### ISSUE THREAD

**Issue by WoMec** [samilliken/openDCIM#775]
When I want to generate report, I get this error

> FPDF error: Image file has no extension and no type was specified: images/

I'm running version 4.2 without any modifications.

**Comment by wilpig** [comment]
Since there's only one report I'll get right on a fix for that.

**Comment by samilliken** [comment]
In case you didn't get it, that was sarcasm.  You need to specify what report you were trying to run, lest we close the issue.  This error usually comes from having an invalid logo file defined.

**Comment by WoMec** [comment]
I have this problem on event report generated by FDPF. True is,  that i dont using logo and that may be the problem. I'll try to configurate some a run report again. If it will be due logo file,  you should add some exception for people who dont use logo file.

**Comment by wilpig** [comment]
We supplied a generic logo file, use it and give us a little credit OR you could use an empty 1px gif.

**Comment by WoMec** [comment]
Ok,  anyway, thank you for tips.
