### ISSUE TITLE
Add ability to search by model in the search bar (already works in the Template page)

### ISSUE THREAD

**Issue by samilliken** [samilliken/openDCIM#778]

**Comment by wilpig** [comment]
That also broke stuff on the template page.

**Comment by samilliken** [comment]
Is there anything still broken on the template page?

**Comment by wilpig** [comment]
Not sure, the last issue was the transferring templates, I think I worked around the formatting issues it caused.

**Comment by samilliken** [comment]
Yeah, you already fixed that.  That was from adding the autosearch field in
the form.  I'm talking about something different, here.
