### ISSUE TITLE
Global Disable, or device disable SNMP polling

### ISSUE THREAD

**Issue by cdcrawford** [samilliken/openDCIM#783]
When I place my devices into DCIM with a management IP, for records keeping, the page attempts to poll the device. This will never get a response, in our environment. 

Could we get a global disable for SNMP polling? Or a disable on the actual device?

**Comment by wilpig** [comment]
If there isn't an snmp community set or it fails to poll the devices three times it won't poll anymore.  On the device page if you have an IP and snmp community set then it might try to poll to get the version of a device and there isn't a way to disable that.

**Comment by cdcrawford** [comment]
I don't have an SNMP community set in the config, as well on the devices. The device still polls for 6 seconds or so, and then returns control.

**Comment by samilliken** [comment]
What version is your install, and what type of device?  Sounds like a
switch, most likely.

Scott

**Comment by wilpig** [comment]
Yes you do or it would just error out immediately because of lack of community.  Check your site config for one.

**Comment by cdcrawford** [comment]
Sam, I'm running 4.2.

Wilbur, See the picture attached.
![capture](https://cloud.githubusercontent.com/assets/3090648/15964173/880929b4-2eed-11e6-8e50-25662af126c6.PNG)

I couldn't find a config file that had configuration settings held within other than the db config.

Am I missing something?

**Comment by wilpig** [comment]
And the device page?  

Going off the assumption by scott that this is a switch the only other snmp lookup a page would get is this:
https://github.com/samilliken/openDCIM/blob/master/classes/SwitchInfo.class.php#L107  which in turn calls this function to do the lookup.
https://github.com/samilliken/openDCIM/blob/master/classes/SwitchInfo.class.php#L123  The first part of the status lookup is a sanity test for the basic info including the community name defined here:
https://github.com/samilliken/openDCIM/blob/master/classes/SwitchInfo.class.php#L28

The only other option is to contact me directly and I can look at your install to see what is going on.

**Comment by cdcrawford** [comment]
Also blank.

The polling is happening on the device.php page, and happens regardless of settings on page load and update.

**Comment by AleSbTNS** [comment]
Dear community, i'm trying to get info from SNMP, and i always receive and blank page as answer. The device is a switch, but i tried with an enviromental sensor too, with the same blank response.

Any ideas?
