### ISSUE TITLE
Add ability to remove/hide "General Store Room"

### ISSUE THREAD

**Issue by s-williamson** [samilliken/openDCIM#785]
I'm not sure if this is feasible or not, I cant see its purpose at a high level. DC level Store Rooms are good but a high level one doesn't really have a purpose

We have 6 Top Level Parent Containers. Each Parent has between 1 to 4 "Sub Containers". The Sub Container level doesn't show any sort of Store Room until it gets down to the actual Datacentre Level where you then see a Storage Room.

There doesn't appear to be a way to move something from a Storage Room to the General Storage Room either. Our Top Level Parent Containers are on different continents.

**Comment by samilliken** [comment]
We have on our list of plans a complete redesign/rewrite of the storage room and salvage processes, so this is a redundant ticket.  Closing.
