### ISSUE TITLE
V4.3: Edit Device Template 

### ISSUE THREAD

**Issue by AndySauer** [samilliken/openDCIM#790]
The link that say "Number of Devices Using This Template: X" show as X the right number of devices, but pressing the link give a list of all devices in openDCIM.
And additional to the complete list the links in that list show names that not match to the target ID that is opened when clicking that link.
On Demo page, for example, you open template for [HP] PROLIANT DL385P and you see there " Number of Devices Using This Template: 1" when clicking you get a longer list. If you click on that list on PP-INTERNAL-DEMARC it opens id15 SAP-S1

**Comment by s-williamson** [comment]
I confirmed on my 4.3 instance this occurs also.
