### ISSUE TITLE
V4.3 Bulk importer unavailable on the menu 

### ISSUE THREAD

**Issue by Jsphdcp31** [samilliken/openDCIM#792]
I'm a new openDCIM user. I start with the 4.3 version and i watched the video on Bulk import. 
But i can't see Bulk importer in my menu ?

is anybody can help me make it appear?
BR

**Comment by wilpig** [comment]
<img width="571" alt="screenshot 2016-07-14 09 34 52" src="https://cloud.githubusercontent.com/assets/1653882/16873480/21701104-4a59-11e6-882e-406e72a93ba3.png">

use the mailing list for questions.
