### ISSUE TITLE
Add ability to turn SNMP off for certain Ports

### ISSUE THREAD

**Issue by outdoorbloke** [samilliken/openDCIM#794]
IT would be nice to have the ability to turn SNMP off for Certain Ports. 
For switches in particular if you add the console port it just takes the stats for the next in line Ethernet port. 
This results in console port being over written and status of the port being incorrect. 

One solution would be a tick box to exempt the port from the SNMP functions

**Comment by wilpig** [comment]
This would require extending the port table out to have an additional field to disable the scanning but in reality if we were to implement this, and it's been discussed, we'd add a field to hold the port id from the snmp scan.  No port id, no status.  It's a two in one solution.  Right now I don't have time to implement it.

**Comment by darklegasy** [comment]
I know have already talked about this feature, but i wanted to add to this issue. We had similar "problems" with some of our switches. When I get port information by SNMP it also pulls information like aggregation ports and sub-interfaces.

**Comment by pigchanc** [comment]
Hi All

my opendcim version currently is 4.3, I am not able to find the detail of snmp setting setup, could you please advise me how to setting snmp which how to know switch port status and got more network device information

**Comment by berriane** [comment]
I also want to know the configuration of SNMP and installation steps.
Thank you for your help

**Comment by samilliken** [comment]
GitHub is not a Q&A forum, it is a bug and enhancement tracking system.  Please refer to the http://www.opendcim.org/participation.html page for information on where the appropriate place to go is.

**Comment by berriane** [comment]
Please I want a forum where I can give questions and have answers about
SNMP configuration, BULK, pass Apache authentication to LDAP authentication
configuration.
Thank you for your help

2016-11-08 13:40 GMT+00:00 Scott Milliken <notifications@github.com>:

**Comment by berriane** [comment]
Here I find nothing

2016-11-08 17:05 GMT+00:00 Mehdi Berriane <berrianemehdi415@gmail.com>:
