### ISSUE TITLE
How to sort Data Center Cabinet ?

### ISSUE THREAD

**Issue by ds2k5** [samilliken/openDCIM#796]
Hello,
how to sort Data Center Cabinet ?
For example there are 11 Racks.

Start with: R3_2
End with: R3_11

then i add a Rack: R3_1, but this Rack is listet after R3_11

Like to have R3_1 at first and not at last position.

![racks](https://cloud.githubusercontent.com/assets/11292286/17164694/fa9a0668-53ca-11e6-8b12-2f34f1a893bb.png)

**Comment by samilliken** [comment]
GitHub issues are for bug reports and feature enhancements.  Please use the mailing list for usability questions.

**Comment by wilpig** [comment]
I'm unable to recreate this as a bug.  Version 4.3 is correctly sorting them.

<img width="198" alt="screenshot 2016-07-27 10 38 20" src="https://cloud.githubusercontent.com/assets/1653882/17181580/42f772fe-53e6-11e6-8f72-9336aac7d9fe.png">
