### ISSUE TITLE
How to build Device/Patchpanel with half size of 19inch ?

### ISSUE THREAD

**Issue by ds2k5** [samilliken/openDCIM#797]
Hi,
how to build Device or Patchpanel with half size of 19 incl.
**and position left or right** ?

We have the issue that i have to represent the following:

R1_1 (19 incl Rack) backside
24 Port Patchpanel

R1_2 (19 incl Rack) backside
24 Port Patchpanel

R1_6 (19 incl Rack) backside
Port: 1 - 12 from R1_1 Port: 1-12
Port: 13-24 from R1_2 Port: 1-12

R1_7 (19 incl Rack) backside
Port: 1 - 12 from R1_1 Port: 13-24
Port: 13-24 from R1_2 Port: 13-24

And we have Devices that are only half size of 19 inch. so
that are two of them in one UE

Thanks

**Comment by samilliken** [comment]
GitHub issues are for bug reports and feature enhancements. Please use the mailing list for usability questions.
