### ISSUE TITLE
Export Connections did not work - Files cloud not be found

### ISSUE THREAD

**Issue by ds2k5** [samilliken/openDCIM#798]
Hello,
if i try to export the connections got Error: 

The Files https://192.168.1.20/export_port_connections.php?deviceid=21 cloud not be found.

In apache errorlog I can found this:

[Wed Jul 27 11:55:20.861721 2016] [:error] [pid 21662] [client 192.168.1.20:38800] PHP Fatal error:  'break' not in the 'loop' or 'switch' context in /var/www/html/openDCIM-4.3/PHPExcel/PHPExcel/Calculation/Functions.php on line 581, referer: https://172.31.12.30/devices.php?DeviceID=21

Using: Ubuntu 16.04.1 (64bit) and openDCIM-4.3
MySQL: 5.7, PHP 7.0.8

How can i fix this ?

Thanks

**Comment by samilliken** [comment]
PHP 7 is not supported, you need to be running PHP 5.x.
