### ISSUE TITLE
Set Label column in fac_DeviceCustomAttribute table to Unique

### ISSUE THREAD

**Issue by wilpig** [samilliken/openDCIM#800]
Opening discussion as to the possible ramifications of adding a unique constraint to the custom attributes labels.  The end result would be that you cannot have a blank like Serial added twice.  Are there any valid use cases where we would want to have a custom attribute multiple times?

**Comment by wilpig** [comment]
The second part of this question is, how do we want to handle mangling the tables in the event that someone has already done this?

**Comment by wilpig** [comment]
In order to add in the custom values to the UpdateDevice function, I'm going to make a simple lookup table with the key set to the custom attribute name and the value being its id number.  From there we can then compare the previous device model to the new model, if a custom attribute is now missing we'll issue the delete and properly log the change.  If a value is different we'll update, again logging.  Lastly if a new value is detected we'll have the id to issue the create and log.

**Comment by Fogest** [comment]
An idea for what to do with the with the duplicate names is to maybe name them something like `name_1`, `name_2`, etc... That way the data is still there. And then still log that such a change has happened. 

I may not know enough about how this system works though so this could be a silly idea.

**Comment by samilliken** [comment]
Is there anything left outstanding on this issue?

**Comment by samilliken** [comment]
Closing.  This appears to be done.
