### ISSUE TITLE
Error Calculating Available RU on DC Summary Page (similar to #774)

### ISSUE THREAD

**Issue by s-williamson** [samilliken/openDCIM#801]
Hi
I am still having issues with this, similar to issue  #774. Something is still doubling up.
                        Infrastructure     Occupied     Allocated     Available
Total U 1512     1219                54                   343                 -104
Percentage       80.6%                 3.6%             22.7%            -6.9%

We have 36x 42RU Racks, 1512 is correct

Running a query against the Datacentre again, I asked each device in it, how many RU they were and if they had a reservation flag. TOTAL RU was 1380, Total Reservations was 345 so total RU in use should be
1035.

**Comment by samilliken** [comment]
If any of your reservations or allocated devices are half depth, they are not counted.

**Comment by samilliken** [comment]
I will check the math on it, again, but half devices will still screw up the numbers.

**Comment by samilliken** [comment]
Committed a fix against #774
