### ISSUE TITLE
Sort sequence of Cabinet Row's - higest cabinetid is on left side

### ISSUE THREAD

**Issue by ds2k5** [samilliken/openDCIM#806]
Hello,
if create Cabinet Rows i have the Problem that
the first created Cabinet in the Cabnetrow is always on the right side

For example create in this sequence: R1_1 (cabinetid=26), R1_2 (cabinetid=27)
then is R1_1 right from R1_2
The higher cabinetid is on the left side.

How to set that R1_1 starts left an R1_2 is right from R1_1 ?

![bildschirmfoto_2016-08-01_06-50-21](https://cloud.githubusercontent.com/assets/11292286/17283886/ce48ab8e-57b5-11e6-9d5f-77d0a793a920.png)

![bildschirmfoto_2016-08-01_06-50-42](https://cloud.githubusercontent.com/assets/11292286/17283889/d487a48c-57b5-11e6-8676-7d3ae72c71b9.png)

Thanks

Dennis

**Comment by wilpig** [comment]
There row layout is determined by their position in the datacenter. Edit the cabinet and put them on the map

On Aug 1, 2016 12:02 AM, ds2k5 <notifications@github.com> wrote:

Hello,
if create Cabinet Rows i have the Problem that
the first created Cabinet in the Row is always on the right side

For example create in this sequence: R1_1 (cabinetid=26), R1_2 (cabinetid=27)
then is R1_1 right from R1_2
The higher cabinetid is on the left side.

How to set that R1_1 starts left an R1_2 is right from R1_1 ?

[bildschirmfoto_2016-08-01_06-50-21]<https://cloud.githubusercontent.com/assets/11292286/17283886/ce48ab8e-57b5-11e6-9d5f-77d0a793a920.png>

[bildschirmfoto_2016-08-01_06-50-42]<https://cloud.githubusercontent.com/assets/11292286/17283889/d487a48c-57b5-11e6-8676-7d3ae72c71b9.png>

Thanks

Dennis

-

**Comment by samilliken** [comment]
Also, please refer to the FAQ.  GitHub issues are not for asking questions
- that's what the mailing list is for.

Scott
