### ISSUE TITLE
Datacenter Permission

### ISSUE THREAD

**Issue by mehranexpert** [samilliken/openDCIM#808]
Hi , Thanks for nice Work , i install last version openDCIM , my question is i want make Two Authentication user Example User A and User B . user A Must see Datacenter A and User B Must just See Datacenter B is it Possible ?

**Comment by samilliken** [comment]
GitHub is not for questions, it is for bug reports and milestone tracking.  Please refer to the FAQ on http://www.opendcim.org and ask your question in the appropriate location.
