### ISSUE TITLE
Language translation not working

### ISSUE THREAD

**Issue by lucamaro** [samilliken/openDCIM#811]
Hi,
I'm having trouble in getting i18n work on my installation. After installing locales on server the only way to get the webapp working is to change: 
      `putenv("LC_ALL=$locale");`
to :
      `putenv("LANGUAGE=$locale");`      

I'm using a docker container with ubuntu 15.04 and php 5.6.4.

Thanks,
Luca

**Comment by wilpig** [comment]
Use the mailing list for help or irc, see the FAQ.
