### ISSUE TITLE
Row View doesn't show Reserved Items

### ISSUE THREAD

**Issue by s-williamson** [samilliken/openDCIM#812]
We have recently planned to add three new Cisco Chassis into one of our DC's. We have added them in to reserve the space (RU13 to RU18 in the screen shot). We have the reservation flag ticked within each of the items but from the Row view it doesn't reflect that that item is a reservation.
![rowview_1](https://cloud.githubusercontent.com/assets/17305720/17504500/e864957e-5e2b-11e6-993d-1c7ad5b2d544.JPG)
![rowview_2](https://cloud.githubusercontent.com/assets/17305720/17504501/e95ac20a-5e2b-11e6-8d4f-7e88f7ff777b.JPG)

**Comment by wilpig** [comment]
https://github.com/samilliken/openDCIM/commit/ceb00b8170669cf5867ed24958bc9e76c229a752
