### ISSUE TITLE
Devices not shown in Cabinet view after upgrade

### ISSUE THREAD

**Issue by digitalwill** [samilliken/openDCIM#813]
Upgraded from 4.0.1 to 4.3 and now when I go into the cabinet view for any cabinet, the rack view does not show the devices that are in that rack.  The cabinet metrics show the correct information and the fac_Device table has all of the cabinet information as well as the label but it is not showing up.  Thanks.

Will

**Comment by wilpig** [comment]
First, use the email list for troubleshooting or irc. Second pull the new installer and upgrade again. Last there is a history in the mailing list archives about the API not working right leading to this type of problem as of version 4.1 or so
