### ISSUE TITLE
Wrong display of used height units

### ISSUE THREAD

**Issue by darklegasy** [samilliken/openDCIM#817]
Noticed the following setting up my OpenDcim environment:

When adding a new device some of the already entered (multi height unit) devices get displayed wrong in the height unit selecter.

Added HPE Bladesystem C7000 into height units 11 to 20:
![capture1](https://cloud.githubusercontent.com/assets/18726527/18079923/718f5736-6e93-11e6-952b-cd43b683c98e.PNG)

Entering new device and see that height unit 20 to 29 is in use:
![capture2](https://cloud.githubusercontent.com/assets/18726527/18079924/74e506f6-6e93-11e6-80ef-7c2e2e461ddc.PNG)

Using OpenDCIM 4.3, PHP 7.0.10, Mysql 5.7.13, Ubuntu 16.04 64-bit

**Comment by wilpig** [comment]
I'll look into it, use normal non upside down racks and it won't be an issue
