### ISSUE TITLE
Cannot pull certain manufacturer

### ISSUE THREAD

**Issue by vobelic** [samilliken/openDCIM#820]
Running 4.3.

Steps to reproduce:
1. Go to repository sync and "Sync manufacturer"
2. Try to sync "Sun/Oracle" (gid=35)
3. Nothing will happen and http server access log should have a similar entry: "PUT /api/v1/manufacturer/Sun/Oracle HTTP/1.1" 404 521

Guessing the "/" in Manufacturer name isn't handled properly?

**Comment by wilpig** [comment]
Adding     AllowEncodedSlashes On to the apache config for the server or the vhost will alleviate this problem.  I think this is a nasty hack and should not be the route approached to fix this.  That being said I did attempt to use urlencoding to make it happy but the server did what it was supposed to and decoded the string and once again got the 404 from slim.

**Comment by samilliken** [comment]
I renamed that manufacturer on the repo to simply 'Sun'.  There's already one for Oracle.  Simple fix for now, and URLENCODING should keep it from popping up again in the future.
