### ISSUE TITLE
API - device PUT doesn't allow storeroom entries (Cabinet = -1)

### ISSUE THREAD

**Issue by abeeson** [samilliken/openDCIM#830]
I've found you just get a Cabinet not found response when trying to insert devices straight into the Storeroom using the device PUT.

Having a look at the API code, the following modification works around this issue:
        if ($cab->CabinetID == "-1") {
                $cab->Rights = "Write";
        }
        if(!$cab->GetCabinet() && $cab->CabinetID =! "-1"){

Instead of this:
        if(!$cab->GetCabinet() {

Whilst bypassing the cabinet existence check for -1 seems ok, forcing the permissions to "Write" for the storeroom as it can't check permissions when the cabinet doesn't exist seems like it would cause some problems. Perhaps checking permissions against the DC (Position data sets it when imported like this) might be workable?

I'd put a pull req in for this, but i'm sure its not suitable with the security hack, so i'm hoping somebody more familiar with the codebase can suggest / implement a better method to make storeroom inserts feasible....

**Comment by wilpig** [comment]
You cannot create items in the storeroom with the regular UI, so we didn't allow it in the API either

**Comment by abeeson** [comment]
Is there a particular reason for that @wilpig, or is it something you would be open to allowing? 

I dont need it via the GUI, but having it via the API would be awesome. I can work around it tbh, but the storeroom is much clearer than using the Zero U field on the racks themselves pre-placement.

**Comment by wilpig** [comment]
The data sanitization isn't set up to allow it. We have a different function that puts things in the storeroom

**Comment by feitingen** [comment]
It would be very convenient to be able to add devices to the storeroom via the API.

I would like to add server shipments to the storerooms as soon as they arrive, as it is easier to keep track of newly arrived stuff that way.

Also, old stuff which are going out are also moved to the storeroom physically, but AFAIK there isn't any API call to move servers to a storeroom other than POSTing to cabinet -1, which also requires tweaking the cabinet permissions.
