### ISSUE TITLE
How can i export cabinet as xls file? look like attachment file.

### ISSUE THREAD

**Issue by naechin91004** [samilliken/openDCIM#832]
Hello.
I want export cabinet as xls file.
How can I do that?
Please help me. Thank you

[cabinet.xlsx](https://github.com/samilliken/openDCIM/files/555531/cabinet.xlsx)

**Comment by samilliken** [comment]
Use the mailing list to ask questions.  Github issues is for reporting bugs or deciding that you are going to contribute to the project by writing some functionality.
