### ISSUE TITLE
Can't FindFirstPort on Switch HP 1810-24

### ISSUE THREAD

**Issue by iskandarzh** [samilliken/openDCIM#840]
I have several switches where openDCIM can't find FirstPort. One of switch type is HP 1810-24. The result of  snmpwalk  from this Switch like this : 
IF-MIB::ifDescr.1 = STRING: Port:  1 FastEthernet - Level
IF-MIB::ifDescr.2 = STRING: Port:  2 FastEthernet - Level
IF-MIB::ifDescr.3 = STRING: Port:  3 FastEthernet - Level
IF-MIB::ifDescr.4 = STRING: Port:  4 FastEthernet - Level
IF-MIB::ifDescr.5 = STRING: Port:  5 FastEthernet - Level
IF-MIB::ifDescr.6 = STRING: Port:  6 FastEthernet - Level
IF-MIB::ifDescr.7 = STRING: Port:  7 FastEthernet - Level
IF-MIB::ifDescr.8 = STRING: Port:  8 FastEthernet - Level
IF-MIB::ifDescr.9 = STRING: Port:  9 FastEthernet - Level

What's suitable regex for this switch to get FindFirstPort?

**Comment by AleSbTNS** [comment]
Dear iskandarzh, did you solve the problem? I'm having the same issue.
