### ISSUE TITLE
Incorrect Markup Key on half depth items

### ISSUE THREAD

**Issue by s-williamson** [samilliken/openDCIM#841]
Hi,
Adding some items to a rack I noticed that the ones that only use half depth are now showing the ownership Markup key of the item using the other half. Mostly it seems it uses the ownership of whats using the back of the rack. As an example I had modded this rack as an example.
![before](https://cloud.githubusercontent.com/assets/17305720/20254004/61157a2a-aa6b-11e6-943d-ab4bf4a111f6.JPG)
Here is my rack. There is several half depth objects in 34/33/31 front only items, 10/8/6 Rear only items.  As you can see the front/rear Markup Color is the same even though the other half is empty
![after](https://cloud.githubusercontent.com/assets/17305720/20254029/adcf3ee6-aa6b-11e6-9279-e4dfdbcb67a1.JPG)
Adding some test blanking plates in, RU33 now shows the color of the newly add blanking plate at the rear. The reservation blanking plate put in to RU10 now has front and rear color set. The other blanking plate in RU8 has now also set the rear color.

**Comment by wilpig** [comment]
Working as expected.

**Comment by s-williamson** [comment]
Huh? How does that make sense? RU10 If it put a reservation item in the front, now looks like the 8 Port Horizontal PDU is a reservation, which it is not. RU 8s front blanking panel which was owned by Red Team now shows it belongs to Yellow team. In previous versions this wasn't an issue. It was fine in either 4.1 or 4.2 (cant remember exactly) but its broken in 4.3.

**Comment by wilpig** [comment]
The coloring is only set per U it has never been split unless by accident some point in the past.

**Comment by s-williamson** [comment]
Just to prove I'm not crazy, I searched through my email trails and found a screen shot I had sent to someone. This was after we had upgraded to 4.1 in mid Feb. You Can see RU39 thru RU36 with a color on the front but white on the rear (nothing in it) , RU 45-53 with yellow on the front and brown at the rear which has some Cable management in it. Wasn't a full screen shot unfortunately so can only show what I have.
![4 1](https://cloud.githubusercontent.com/assets/17305720/20296238/aab61ce6-ab44-11e6-884f-e6911427a70e.JPG)
