### ISSUE TITLE
Make it possible to give cables a name/number

### ISSUE THREAD

**Issue by ody666** [samilliken/openDCIM#854]
In the discussion list we have several messages about a missing possibility to give cables names or numbers.
For example on a switch not only Media Type and Color Code, also cable name/number should be registered.

**Comment by wilpig** [comment]
Function already exists as stated on the email list.

**Comment by wilpig** [comment]
<img width="1094" alt="screenshot 2017-02-03 07 35 19" src="https://cloud.githubusercontent.com/assets/1653882/22593275/5da7239a-e9e3-11e6-9ec5-69c4c1ccb1ff.png">

**Comment by ody666** [comment]
yes i know the suggestions with the Notes information on the switch. But the Notes information are coming from the switch port configuration over snmp. the network guys normally describing there information based on the port-configuration. they are not interested about cabling information...

**Comment by wilpig** [comment]
Did that note come from the switch?  No.  That information doesn't come from the switch unless you tell it to pull from the switch.  This is a problem of user education versus missing feature.
