### ISSUE TITLE
Custom Device Values still added to table when Custom Device Attribute no longer exists

### ISSUE THREAD

**Issue by JaredMurray** [samilliken/openDCIM#855]
When working with multiple tabs open or with multiple users: If someone removes a Custom Device Attribute using the "configuration.php" while someone also has a "devices.php" page open, Issues can arise. If the devices.php was opened before the removal of the Custom Device Attribute, then the device page will still have the Custom Device Attribute field and its value in the form. If the form is submitted, then the device page breaks (as well as, the cabinet view with that device, the row view with that device, and network connections to that device). pages containing this device or information from this device never finish loading.

It seems that there is no check to see if the custom device attribute still exists when the device updates. Values are still written to fac_DeviceCustomValue. The only way I have found to fix the issue is to go into fac_DeviceCustomValue and delete the offending row.

**Comment by wilpig** [comment]
This has been solved via #800
