### ISSUE TITLE
Error while installation

### ISSUE THREAD

**Issue by irfannaseefp** [samilliken/openDCIM#858]
In the first run , After getting all the checks good, I got redirected to URL _install.php?preflight-ok_ with a blank page. I checked the database, all the tables are created. Is this blank page supposed to come or is it an error ? I did not get any confirmation of succesfull completion. So i searched through the code and i can see that there is a line   `require_once( "elogs/vanderbilt.inc.php" );` in **facilities.inc.php**. But I cannot see any folder named elogs in the source. Downloaded version is openDCIM-4.3.1

**Comment by wilpig** [comment]
You pulled from GitHub. That isn't 4.3.1

On Feb 22, 2017 5:58 AM, irfannaseefp <notifications@github.com> wrote:

In the first run , After getting all the checks good, I got redirected to URL install.php?preflight-ok with a blank page. I checked the database, all the tables are created. Is this blank page supposed to come or is it an error ? I did not get any confirmation of succesfull completion. So i searched through the code and i can see that there is a line require_once( "elogs/vanderbilt.inc.php" ); in facilities.inc.php. But I cannot see any folder named elogs in the source. Downloaded version is openDCIM-4.3.1
