### ISSUE TITLE
Type error in PDU usage calculation

### ISSUE THREAD

**Issue by sebkoe** [samilliken/openDCIM#860]
Depending on the input the wattage calculation starting at https://github.com/samilliken/openDCIM/blob/master/classes/PowerDistribution.class.php#L398 can lead to $watts being a float type. However 'Wattage' is of the type int in the database table fac_PDUStats. So in cases when $watts is a float the insert into the table fails. I think the best way to handle this is to change the column type in the table to float.

**Comment by samilliken** [comment]
In 12 years this has never been an issue.  MySQL simply truncates the input
to an int value.  This sounds like a configuration specific issue - can you
provide details on your setup?

Scott

**Comment by sebkoe** [comment]
There is nothing special about my setup.

Ubuntu 14.04
 - default mariadb installation from the ubuntu repos
 - default apache from the ubuntu repos
 - default php from the ubuntu repos

I currently don't have access to the PDU to use real life data but I can reproduce it by adding $watts=123.4; just in one line above the SQL-Statement in https://github.com/samilliken/openDCIM/blob/master/classes/PowerDistribution.class.php#L421.

> php /var/www/dcim/poll_pdu_stats.php
>
>PowerDistribution::UpdateStats::PDO Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '4,LastRead=now() ON >DUPLICATE KEY UPDATE Wattage=123,4, LastRead=now()' at line 1 SQL=INSERT INTO fac_PDUStats SET PDUID=839, Wattage=123,4,LastRead=now() ON DUPLICATE KEY UPDATE Wattage=123,4, LastRead=now();

I just took a closer look at the error message. It actually says "Wattage=123,4" with a comma instead of a dot. I do have the locale set to de_DE. The bug is not that it is using the wrong type but that [this](https://stackoverflow.com/questions/17587581/php-locale-dependent-float-to-string-cast) PHP 'feature' is screwing up the string casting.
