### ISSUE TITLE
Skip switch polling if tag 'NoPoll' has been added to a device

### ISSUE THREAD

**Issue by samilliken** [samilliken/openDCIM#865]
Lots of my switches I can't get to, but the IP/DNS name is in there for documentation purposes.  Simply allow this as a mechanism to skip polling on ones I don't want.

**Comment by tb-killa** [comment]
#Bump 
In our large Installation we have around 40 Switches which are only for Dokumentation exists.
These are from another Company but we got there some Ports (VLAN Based) to our Infrastructure.
Know it loads long because it checked for snmp polling.
