### ISSUE TITLE
Show Child Objects on Select Tree

### ISSUE THREAD

**Issue by tb-killa** [samilliken/openDCIM#870]
Hello everyone.
I like your Software.
If you build Trees on Container like this:

House1
-> Room1
-> Room2

House2
-> Room1
-> Room2

You dont see the related Tree if you build new Container as Parent or a new Data Center on one of these Container.

It would be great if the View would be like this:

:New Container
Parent Container: "House2 > Room1" 

Actually it shows like this:
:New Container
Parent Container:
-> Room2
-> Room2
-> Room1
-> Room1
-> House2
-> House1

**Comment by wilpig** [comment]
If I am following you correctly that wouldn't be feasible because it would make the navigation tree expand out horizontally to the point to where it wouldn't fit in the space we have allotted making it unwieldy.  Below here is an example of the current structure of nested containers.

<img width="207" alt="screenshot 2017-03-29 09 09 50" src="https://cloud.githubusercontent.com/assets/1653882/24458762/7bd6b654-145f-11e7-8caf-c729904e9b52.png">

**Comment by tb-killa** [comment]
I will show you what i mean:

Thats my Tree with Container and DataCenter(s).

![image](https://cloud.githubusercontent.com/assets/932481/24465097/3dccef84-14ac-11e7-9edd-7731ecdb2689.png)


Now i will build a new DataCenter on some of these Container.

I Select new Datacenter, give Name and now Select Container ... but which is now the right ?? ...

![image](https://cloud.githubusercontent.com/assets/932481/24465045/1331f102-14ac-11e7-9801-4c766415d0db.png)

**Comment by tb-killa** [comment]
Maybe someone could help to find a fast fix.
I search inside the cabinet and datacenter class files and found in the cabine class file two function calls:
function GetChildren() and function GetChildContainerList()

Maybe some of the Devs could use these for the section field of SubContainer to get a coherently dropdown.

**Comment by wilpig** [comment]
That would't be done in the class but would be applied at the client end in the container management screen or wherever you took that screenshot from without any context.

**Comment by tb-killa** [comment]
>  or wherever you took that screenshot from without any context.
Dont know what you mean ...
The First one is the Tree on the Left Side (Sidebar).
The Second one is from the "Edit Datacenters" Side

**Comment by tb-killa** [comment]
If someone would like to Replicate my Issue:
Create Main Container with different Names and after that build Parent Containers with same Names on both Main Container. Now Create new Datacenter and Select Container .. you see that the Child Container are not Structured to the Parent ones .. Like the Second Screenshot you see.

**Comment by wilpig** [comment]
I'm not going to recreate your problem.  You are welcome to log into the dev instance I use and replicate the problem.  http://dev.opendcim.org  l/p  dcim/dcim   Here is some JS that will do about what you want, I think.

Goto the datacenter editing page. In your browser hit F12 to bring up the dev tools.  Paste this in the console window.
`$('#container > option[value!=0]').each(function(){
  var option=this;
  var cont=$('#datacenters a[href$="container='+this.value+'"]');
  cont.parentsUntil('ul#datacenters.mktree').each(function(){
    var cur_label=$(this).prev('a').text();
    if(cur_label.trim()!=""){
      option.text=cur_label+' > '+option.text;
    }
  });
});
`

**Comment by tb-killa** [comment]
Damn .. that works=)
Thats great ... will this be a Commit or at the time now only a simple fast fix ?

**Comment by wilpig** [comment]
we're discussing it on irc.  This is used in a few places and needs to be adjusted to work for all of them in a uniform fashion

**Comment by tb-killa** [comment]
Sounds Great.
First of all Thanks for these great and Quick Help.
