### ISSUE TITLE
Header Font Color depent on selected Background Color

### ISSUE THREAD

**Issue by tb-killa** [samilliken/openDCIM#871]
If you select white Header Color there must be some logic or adding selecting own Font Color to change them.

Also there must be an Option to select the disable the text-shadow or change the Color.
It doesn´t look good if you select white background!

**Comment by samilliken** [comment]
Pull requests are welcome.

**Comment by wilpig** [comment]
Shadow working as a border on a light background, as intended.  Yes it's a little weird based on the browser rendering but the border could be toned down to 1px and make it smoother.

<img width="1357" alt="screenshot 2017-03-29 09 18 51" src="https://cloud.githubusercontent.com/assets/1653882/24459275/bf57449c-1460-11e7-86bb-c71dbc23d14b.png">
