### ISSUE TITLE
Insert Network Type LWL (ST / SC-Duplex / Mini-LC) for Patchpanel and Multiple Connections to SwitchPort

### ISSUE THREAD

**Issue by tb-killa** [samilliken/openDCIM#873]
We have a large LWL Installation (86 Patchpanels) where we only use ST-Patchpanels. So there are 12 or 24 single ST Bajonett Connector on the Patchpanel (One Tx (Red) and One Rx (Black)).
Now on the other Side there are the Switches ... Most of them use the new Mini-LC Connector but there are also some Modulare Ones who use SC-Duplex.
It would be great if I could use one Port of the Switch and Connect them to the Patchpanel.
Warning: It could be that some of the Fasers are Broken. Now I have to Connect ST-Patchpanel Port 1 and ST-Patchpanel Port 3 because 2 ist broken.
I need the direct Connection because we use the Path Function to show if something is failured.

I hope you know what I mean ?

![image](https://cloud.githubusercontent.com/assets/932481/24894910/9dad56b0-1e8d-11e7-896a-64f0438d1006.png)

**Comment by samilliken** [comment]
This has been discussed before and there are workarounds.  None of the active developers wishes to work on this, so for any traction to happen on it, someone would have to be motivated to contribute code.
