### ISSUE TITLE
Safari rendering bug

### ISSUE THREAD

**Issue by samilliken** [samilliken/openDCIM#876]
Known issue, unable to find a reliable fix.

![safari rendering bug](https://cloud.githubusercontent.com/assets/1653883/25088806/27ee33f4-2347-11e7-9126-7f5fee877915.png)

**Comment by samilliken** [comment]
https://www.reddit.com/r/webdev/comments/273qoo/safari_and_subpixel_rendering/

**Comment by wilpig** [comment]
This has been fixed
