### ISSUE TITLE
Add local Users

### ISSUE THREAD

**Issue by arvoa** [samilliken/openDCIM#878]
Hello everyone, 

I started using OpenDCIM a few months ago and was the only user accessing the site at the time. Over time now more users would like to start accessing the site. Is there anyway to add local users and give them restricted access to the site?

Version 4.3.1
Oracle Linux 7 64 bit

Thanks in advance. 

Andrew

**Comment by samilliken** [comment]
Please use the discussion mailing list for asking questions.  GitHub is for tracking open issues.  The answer is, no - openDCIM doesn't mangle your authentication mechanism for you.
