### ISSUE TITLE
report panel schedule php error.

### ISSUE THREAD

**Issue by ThomasADavis** [samilliken/openDCIM#886]
PHP Fatal error:  Call to a member function find() on a non-object in /var/www/openDCIM/report_panel_schedule.php on line 213, referer: https://dae-dc.nersc.gov/report_panel_schedule.php

Not sure what is going on here..

**Comment by samilliken** [comment]
Ok, figured out that this is mainly a nuisance bug.  It does that when there's nothing to report.  Will add in some code to bypass when there's nothing to do.
