### ISSUE TITLE
Report "Search/Export by Datacenter" has problem with Custom Atributes on chassis

### ISSUE THREAD

**Issue by WoMec** [samilliken/openDCIM#894]
When some custom atribute is set, "Search/Export report" returns following error for row, where is chassis device

![image](https://cloud.githubusercontent.com/assets/7909801/26450052/ccf2a07a-4155-11e7-8e05-029db36e67dc.png)

Maybe some problem with child devices?

**Comment by timlegge** [comment]
Anyone have an update on this one?  Just ran into the error myself

**Comment by timlegge** [comment]
I replaced search_export.php with the version from my 4.2 install and it seems to work for now.

**Comment by timlegge** [comment]
This appears to fix the issue:

```
--- /tmp/openDCIM-4.4/search_export.php 2017-05-22 08:44:12.000000000 -0300
+++ search_export_4.4.php       2017-05-27 21:01:24.300363988 -0300
@@ -148,7 +148,8 @@
                                        \t<td>$ctags</td>
                                        \t<td>$cDepartment</td>
           \t<td>$cwarranty</td>
-                                       \t<td>$cdate</td>\n\t\t</tr>\n";
+                                       \t<td>$cdate</td>
+                                       {$ca_cells}\t\n\t\t</tr>\n";
                                }
                        }
                }
```

**Comment by WoMec** [comment]
Last added line should looks like this: 
`\t{$ca_cells}\n\t\t</tr>\n";`
