### ISSUE TITLE
report_contact.php Call to undefined method ESX::GetVMListbyOwner()

### ISSUE THREAD

**Issue by ChrisJergens** [samilliken/openDCIM#898]
I had to change L540 to VM() instead of ESX() because this method is in VM.class.php not ESX.class.php
https://github.com/samilliken/openDCIM/blob/master/report_contact.php#L540

Otherwise page fails to load and logs PHP Fatal error:  Call to undefined method ESX::GetVMListbyOwner() in /var/www/html/report_contact.php on line 543

**Comment by samilliken** [comment]
Had already been fixed, but not marked as complete.
