### ISSUE TITLE
After update 4.3.1 -> 4.4 copy/add buttons for devices not work

### ISSUE THREAD

**Issue by Nefelim4ag** [samilliken/openDCIM#913]
After update 4.3.1 -> 4.4 copy/add buttons not work, how i can debug this?
Thanks.

**Comment by samilliken** [comment]
Please move this to the discussion mailing list.  Need to know what browser
you're using.  Try to replicate the problem on the online demo website - if
you can't replicate it there, it's a local issue.

Scott

**Comment by samilliken** [comment]
Unable to replicate.

**Comment by Nefelim4ag** [comment]
Problem has self fixed (after update system and several reboots), anyway, thanks.
