### ISSUE TITLE
Can't search existing patch by label/port

### ISSUE THREAD

**Issue by kuzabi** [samilliken/openDCIM#926]
Hello,
in current version when device port is used/connected to another device, this specific port disapear from a list in "View path connection --> Serach by label/port".
So it's impossible to view existing connections from this place.

Are you able to confirm that it a bug?

Best regards

**Comment by tb-killa** [comment]
Yes i´v got the same Results.
The Connection exists if i go to the Device like Interface 1/0/47 but on the View-Path-Connection i could select only all the disconnected Ports not the needing one who exists.

Please fix because we need this Function in the near of Future.

**Comment by tb-killa** [comment]
I think i fix this:

Change: 

https://github.com/samilliken/openDCIM/blob/39bf384cabbfa13a848a0dd2b35fe8da3c656ceb/pathmaker.php#L69

to: `$ports=($dev->Rights=="Write")?$dp->getPorts():array();`

After this i could select now the connected Ports.
