### ISSUE TITLE
My OpenDcim Just display report menu

### ISSUE THREAD

**Issue by alvianaufan** [samilliken/openDCIM#940]
Halo Guys,

I have a problem with my OpenDCIM like this : 

![problem opendcim](https://user-images.githubusercontent.com/29045490/28902871-e6e4bd12-782b-11e7-9d63-f6b23774c0ee.PNG)

My OpenDcim not show display more menu after me rename the user in user administration menu.
Now at my opendcim just show report menu. 
Previously, the menu in my opendcim is complete, including templates, cabinet, configuration and others

Please help me, how to fix it.

**Comment by wilpig** [comment]
Address all questions to the mailing list.

**Comment by alvianaufan** [comment]
ill try install opendcim in local network

**Comment by alvianaufan** [comment]
previously, the menu is normal and complete

and after i rename my user administration, the webpage is reloading and the menu is lost except report  menu

**Comment by JL07** [comment]
I have the same issue...
