### ISSUE TITLE
Port map does not show for rear ports on cross connected patch panels

### ISSUE THREAD

**Issue by wilpig** [samilliken/openDCIM#949]
When clicking on the rear port link on a patch panel that has cross connected front ports like this example:
<img width="941" alt="screenshot 2017-08-22 09 22 24" src="https://user-images.githubusercontent.com/1653882/29570246-835f186a-871b-11e7-89e7-c8b9ce13f01c.png">

You get the following poop up instead of the port map:
<img width="414" alt="screenshot 2017-08-22 09 23 34" src="https://user-images.githubusercontent.com/1653882/29570316-b9481238-871b-11e7-94fd-d29598e8a36b.png">

This is being caused by a bad assumption in the GotoHeadDevice() function at https://github.com/samilliken/openDCIM/blob/master/classes/ConnectionPath.class.php#L65

When the link is clicked we process the port that it is currently on and add the front and rear ports to the lookup table.  As we go down the chain to the next port, which is the other front port, we add in the front and rear ports as well as the connecting device's port.  The error is because we already have this device and port combination in the table from our initial click.  Instead of returning an error on line 85 we need to rethink this process.

**Comment by TafThorne** [comment]
> You get the following **poop** up instead of the port map:

I would hope for a pop up instead of a poop 💩 up.

**Comment by wilpig** [comment]
https://github.com/samilliken/openDCIM/blob/416de4ed9e936b0fe20eaf01b41dedb4da2e5664/departments.php#L123
https://github.com/samilliken/openDCIM/blob/416de4ed9e936b0fe20eaf01b41dedb4da2e5664/device_templates.php#L366
https://github.com/samilliken/openDCIM/blob/416de4ed9e936b0fe20eaf01b41dedb4da2e5664/usermgr.php#L114

It wasn't a typo.

**Comment by TafThorne** [comment]
Thank you for confirming.

**Comment by wilpig** [comment]
<img width="449" alt="screenshot 2017-09-19 20 49 44" src="https://user-images.githubusercontent.com/1653882/30623264-1ac80b3c-9d7c-11e7-81d4-972064f13c19.png">
