### ISSUE TITLE
Provide only PathDrawing Screen Printing

### ISSUE THREAD

**Issue by tb-killa** [samilliken/openDCIM#954]
It would be great if we could Print the PathDrawing Screen of the specified selected Connection alone.
Actually you click on the Port of the Device, the PathDrawing Screen shows but if you would print there is everything.

**Comment by wilpig** [comment]
<img width="452" alt="screenshot 2017-09-19 21 35 54" src="https://user-images.githubusercontent.com/1653882/30624362-8b9ff22e-9d82-11e7-97e1-e7dc9761d4eb.png">

Example of newly added print path button
