### ISSUE TITLE
Redirection on non standard ports

### ISSUE THREAD

**Issue by lucamaro** [samilliken/openDCIM#963]
Hi all,
if dcim is exposed on non stardard port (not 80 or no 443) redirection is not working properly, because port is omitted in the redirecting URL.

When deploying behind a reverse proxy this break the apache ProxyPassReverse directive which cannot intercept properly the Location header, leaving unaltered the redirection address.

Thank you,
Luca

**Comment by wilpig** [comment]
I don't think we can detect what port it is running on to spend to the url. Pretty sure you're just going to have to run on a standard port

**Comment by wilpig** [comment]
For the record I use a reverse proxy on my setup but my external side is on 443 and 80 the internal for that I think is 8443.

**Comment by lucamaro** [comment]
$_SERVER['PORT']  contains the infromation you need. I can provide a patch if you want.

**Comment by wilpig** [comment]
But that will break in my case.  So to make this do what you want we’d have to supply a place in the configuration for the end user to supply the URL base to hand back in the redirection function.  It’s a problem that shouldn’t exist if you use a standard name and not try to pull some security through obscurity nonsense.

**Comment by lucamaro** [comment]
Sorry but I don't understand your setup. Shouldn't be everything behind reverse proxy? Which is the scenario that breaks?

The configuration option is widely used. And using docker it's likely you are going to serve on non standard port on backend.

**Comment by wilpig** [comment]
My front end host is dev.opendcim.org port 443 and that is proxied from 10.0.0.253:8443

The redirect works because I'm using a real reverse proxy that hides the nonsense I'm running in the background

On Oct 9, 2017 11:50 AM, Luca <notifications@github.com> wrote:

Sorry but I don't understand your setup. Shouldn't be everything behind reverse proxy? Which is the scenario that breaks?

The configuration option is widely used. And using docker it's likely you are going to serve on non standard port on backend.

**Comment by lucamaro** [comment]
After some tests, I realized that in version 4.3 everything worked fine. Things changed after merging patch for issue #885 where HTTP_HOST was replaced by SERVER_NAME in `redirect` function. The former value contains port, the second does not. 

Again... this apache configuration works properly if dcim returns an url which is intercepted (url in Location header MUST contain port 8443):

    ProxyPass / https://10.0.0.253:8443/
    ProxyPassReverse / https://10.0.0.253:8443/

So you have to use HTTP_HOST or construct url concatenating SERVER_PORT to SERVER_NAME.
