### ISSUE TITLE
device connection notes are replaced by color code.

### ISSUE THREAD

**Issue by jmcbxl** [samilliken/openDCIM#983]
Hello

A device has got some connections.
For these connections you can chose a 'color code' (scrolling list last column).
When I update that color code, the value gets placed in the note field too. So the previous value of the note field gets lost.

Is it a bug or a misuse of the note field ?

**Comment by samilliken** [comment]
Sounds like a bug.

Scott

**Comment by wilpig** [comment]
Can't reproduce.
