### ISSUE TITLE
Zone Statistics not calculated correctly in v4.5

### ISSUE THREAD

**Issue by dmbanke** [samilliken/openDCIM#990]
With the upgrade from v4.3.1 to 4.5 in our Test environment with a copy of our Prod data, I noticed that  the Allocated RU statistics had increased and I also had negative values for my Available RU in some of my Zones. The Occupied and Allocated also showed the same values.

I tried this in the demo site and noticed that in the Zone both the Allocated and Occupied RU numbers where being added to when ever I added a new device which did not have the reservation flag on it. This is not the case for DCs.

[Zone Statistics Issue.pdf](https://github.com/samilliken/openDCIM/files/1516277/Zone.Statistics.Issue.pdf)

**Comment by samilliken** [comment]
As far as I can tell, this is fixed.    Unfortunately I have far too many items in my dataset at work to hand verify it.   In my smaller development dataset, I did hand verify it.

**Comment by dmbanke** [comment]
I just tested this with the 18.01 release. My small DC of 8 x 42RU cabinets that happen to be fully utilized with no Infrastructure items, shows as Occupied 336, Allocated 336 and Available -336.

**Comment by dmbanke** [comment]
In further testing with my larger DC, 10k+ devices, I noticed the Infrastructure number did go down and I was able to correlate it to the number of devices in Storage.
