### ISSUE TITLE
Report not displaying custom attributes for members of a chassis

### ISSUE THREAD

**Issue by ChadH1** [samilliken/openDCIM#996]
I have custom attributes set up for servers (to display things like procs, ram, etc).  When I use the Search/Export by Data Center, I notice that, while rack mount servers will display the contents of their custom attributes, the servers that are blades and are part of a chassis are blank.

![screenshot](https://user-images.githubusercontent.com/34547451/34000199-32ec6b58-e0b2-11e7-9ed1-8c99550784c4.png)

**Comment by vinod-wagh** [comment]
Hi,
 I am facing the same issue with the version 18.01.

**Comment by vinod-wagh** [comment]
Hello Team,

This issue has been fix today only I checked it and test it in my
environment.

Thank you so much.

-----
Thanking You,
  Vinod Wagh
GSM +91 98231 65559
