### ISSUE TITLE
Daisy Chain Cdu's?

### ISSUE THREAD

**Issue by goldfoxweb** [samilliken/openDCIM#999]
Is it possible to enable us to link PDU's together?

At the moment we have some automatic transfer switches (ATS) that are not fed directly from a power panel but a port on a CDU we then have another CDU being fed from that for our devices that don't have dual power supplies.

At the moment is doesn't seem possible to link them altogether. We have worked round this by making the ATS a device with 3 power connections and using port labels to define direction, this doesn't seem the best method.

**Comment by samilliken** [comment]
GitHub is now a Q&A forum, it is an issue tracking system.   Please direct your questions to the mailing list.   Yes, there is a "hack" for what you are asking about.   Move the conversation to the mailing list and I'll answer there.

**Comment by goldfoxweb** [comment]
My apologies i should of said "Would it be possible!"
